use strum_macros::IntoStaticStr;

#[derive(Copy, Clone, Debug, PartialEq, Eq, IntoStaticStr, Hash, PartialOrd, Ord)]
#[strum(serialize_all = "snake_case")]
#[cfg(feature = "vic3")]
pub enum Item {
    Accessory,
    AccessoryTag,
    AccessoryVariation,
    AccessoryVariationLayout,
    AccessoryVariationTextures,
    Asset,
    Attitude,
    BattleCondition,
    BlendShape,
    BuildingGroup,
    BuildingType,
    CanalType,
    Country,
    Culture,
    CustomLocalization,
    Define,
    Dlc,
    DlcFeature,
    EffectLocalization,
    Entity,
    Ethnicity,
    Event,
    EventNamespace,
    File,
    GameConcept,
    GeneAgePreset,
    GeneAttribute,
    GeneCategory,
    Goods,
    Ideology,
    Institution,
    InterestGroup,
    InterestGroupTrait,
    LawGroup,
    LawType,
    Localization,
    MapLayer,
    MediaAlias,
    Modifier,
    NamedColor,
    Pdxmesh,
    PopType,
    PortraitAnimation,
    ProductionMethod,
    ProductionMethodGroup,
    Province,
    Religion,
    ScriptedEffect,
    ScriptedGui,
    ScriptedList,
    ScriptedModifier,
    ScriptedTrigger,
    ScriptValue,
    Sound,
    StateRegion,
    StateTrait,
    StrategicRegion,
    Technology,
    TechnologyEra,
    Terrain,
    TerrainLabel,
    TerrainManipulator,
    TerrainMask,
    TerrainMaterial,
    TextureFile,
    TransferOfPower,
    TriggerLocalization,
}

impl Item {
    #[cfg(feature = "vic3")]
    pub fn path(self) -> &'static str {
        #[allow(clippy::match_same_arms)]
        match self {
            Item::Accessory => "gfx/portraits/accessories/",
            Item::AccessoryTag => "gfx/portraits/accessories/",
            Item::AccessoryVariation => "gfx/portraits/accessory_variations/",
            Item::AccessoryVariationLayout => "gfx/portraits/accessory_variations/",
            Item::AccessoryVariationTextures => "gfx/portraits/accessory_variations/",
            Item::Asset => "gfx/models/",
            Item::Attitude => "",
            Item::BattleCondition => "common/battle_conditions/",
            Item::BlendShape => "gfx/models/",
            Item::BuildingGroup => "common/building_groups/",
            Item::BuildingType => "common/buildings/",
            Item::CanalType => "common/canals/",
            Item::Country => "common/country_definitions/",
            Item::Culture => "common/cultures/",
            Item::CustomLocalization => "common/customizable_localization/",
            Item::Define => "common/defines/",
            Item::Dlc => "",
            Item::DlcFeature => "",
            Item::EffectLocalization => "common/effect_localization/",
            Item::Entity => "gfx/models/",
            Item::Ethnicity => "common/ethnicities/",
            Item::Event => "events/",
            Item::EventNamespace => "events/",
            Item::File => "",
            Item::GameConcept => "common/game_concepts/",
            Item::GeneAgePreset => "common/genes/",
            Item::GeneAttribute => "gfx/models/",
            Item::GeneCategory => "common/genes/",
            Item::Goods => "common/goods/",
            Item::Ideology => "common/ideologies/",
            Item::Institution => "common/institutions/",
            Item::InterestGroup => "common/interest_groups/",
            Item::InterestGroupTrait => "common/interest_group_traits/",
            Item::LawGroup => "common/law_groups/",
            Item::LawType => "common/laws/",
            Item::Localization => "localization/",
            Item::MapLayer => "gfx/map/map_object_data/layers.txt",
            Item::MediaAlias => "gfx/media_aliases/",
            Item::Modifier => "common/modifiers/",
            Item::NamedColor => "common/named_colors/",
            Item::Pdxmesh => "gfx/models/",
            Item::PopType => "common/pop_types/",
            Item::PortraitAnimation => "gfx/portraits/portrait_animations/",
            Item::ProductionMethod => "common/production_methods/",
            Item::ProductionMethodGroup => "common/production_method_groups/",
            Item::Province => "map_data/provinces.png",
            Item::Religion => "common/religions/",
            Item::ScriptedEffect => "common/scripted_effects/",
            Item::ScriptedGui => "common/scripted_guis/",
            Item::ScriptedList => "common/scripted_lists/",
            Item::ScriptedModifier => "common/scripted_modifiers/",
            Item::ScriptedTrigger => "common/scripted_triggers/",
            Item::ScriptValue => "common/script_values/",
            Item::Sound => "",
            Item::StateRegion => "map_data/state_regions/",
            Item::StateTrait => "common/state_traits/",
            Item::StrategicRegion => "common/strategic_regions/",
            Item::Technology => "common/technology/technologies/",
            Item::TechnologyEra => "common/technology/eras/",
            Item::Terrain => "common/terrain/",
            Item::TerrainLabel => "common/labels",
            Item::TerrainManipulator => "common/terrain_manipulators/",
            Item::TerrainMask => "gfx/map/masks/",
            Item::TerrainMaterial => "gfx/map/terrain/materials.settings",
            Item::TextureFile => "gfx/models/",
            Item::TransferOfPower => "common/government_types/",
            Item::TriggerLocalization => "common/trigger_localization/",
        }
    }
}
