use std::sync::LazyLock;

use crate::everything::Everything;
use crate::helpers::TigerHashMap;
use crate::hoi4::tables::misc::*;
use crate::item::Item;
use crate::scopes::*;
use crate::token::Token;
use crate::trigger::Trigger;

use Trigger::*;

pub fn scope_trigger(name: &Token, _data: &Everything) -> Option<(Scopes, Trigger)> {
    let name_lc = name.as_str().to_ascii_lowercase();
    TRIGGER_MAP.get(&*name_lc).copied()
}

static TRIGGER_MAP: LazyLock<TigerHashMap<&'static str, (Scopes, Trigger)>> = LazyLock::new(|| {
    let mut hash = TigerHashMap::default();
    for (from, s, trigger) in TRIGGER.iter().copied() {
        hash.insert(s, (from, trigger));
    }
    hash
});

/// LAST UPDATED HOI4 VERSION 1.16.4
/// See `documentation/triggers_documentation.md` from the game files.
/// TODO HOI4
const TRIGGER: &[(Scopes, &str, Trigger)] = &[
    (Scopes::None, "add_to_temp_array", UncheckedValue),
    (Scopes::None, "add_to_temp_variable", UncheckedValue),
    (Scopes::Character, "advisor_can_be_fired", UncheckedValue),
    (Scopes::Country, "agency_upgrade_number", UncheckedValue),
    (Scopes::Country, "ai_has_role_division", UncheckedValue),
    (Scopes::Country, "ai_has_role_template", UncheckedValue),
    (Scopes::Country, "ai_irrationality", UncheckedValue),
    (Scopes::Country, "ai_liberate_desire", UncheckedValue),
    (Scopes::Country, "ai_wants_divisions", UncheckedValue),
    (Scopes::Country, "all_active_scientist", UncheckedValue),
    (Scopes::Country, "all_allied_country", UncheckedValue),
    (Scopes::Country, "all_army_leader", UncheckedValue),
    (Scopes::Country, "all_character", UncheckedValue),
    (Scopes::Country, "all_controlled_state", UncheckedValue),
    (Scopes::Country, "all_core_state", UncheckedValue),
    (Scopes::None, "all_country", UncheckedValue),
    (Scopes::None, "all_country_with_original_tag", UncheckedValue),
    (Scopes::Country, "all_enemy_country", UncheckedValue),
    (Scopes::Country, "all_guaranteed_country", UncheckedValue),
    (Scopes::Country, "all_military_industrial_organization", UncheckedValue),
    (Scopes::Country, "all_navy_leader", UncheckedValue),
    (Scopes::Country, "all_neighbor_country", UncheckedValue),
    (Scopes::State, "all_neighbor_state", UncheckedValue),
    (Scopes::Country, "all_occupied_country", UncheckedValue),
    (Scopes::None, "all_of", UncheckedValue),
    (Scopes::None, "all_of_scopes", UncheckedValue),
    (Scopes::Country.union(Scopes::Operation), "all_operative_leader", UncheckedValue),
    (Scopes::None, "all_other_country", UncheckedValue),
    (Scopes::Country, "all_owned_state", UncheckedValue),
    (Scopes::Country, "all_purchase_contracts", UncheckedValue),
    (Scopes::Country, "all_scientists", UncheckedValue),
    (Scopes::None, "all_state", UncheckedValue),
    (Scopes::Country, "all_subject_countries", UncheckedValue),
    (Scopes::Country, "all_unit_leader", UncheckedValue),
    (Scopes::Country, "alliance_naval_strength_ratio", UncheckedValue),
    (Scopes::Country, "alliance_strength_ratio", UncheckedValue),
    (Scopes::None, "always", UncheckedValue),
    (Scopes::Country, "amount_manpower_in_deployment_queue", UncheckedValue),
    (Scopes::Country, "amount_research_slots", UncheckedValue),
    (Scopes::Country, "amount_taken_ideas", UncheckedValue),
    (Scopes::None, "and", UncheckedValue),
    (Scopes::Country, "any_claim", UncheckedValue),
    (Scopes::State, "any_country_with_core", UncheckedValue),
    (Scopes::Country, "any_guaranteed_country", UncheckedValue),
    (Scopes::Country, "any_home_area_neighbor_country", UncheckedValue),
    (Scopes::None, "any_of", UncheckedValue),
    (Scopes::None, "any_of_scopes", UncheckedValue),
    (Scopes::Country.union(Scopes::Operation), "any_operative_leader", UncheckedValue),
    (Scopes::State, "any_province_building_level", UncheckedValue),
    (Scopes::None, "any_state_in", UncheckedValue),
    (Scopes::Country, "any_war_score", UncheckedValue),
    (Scopes::State, "area", UncheckedValue),
    (Scopes::Combatant, "armor", UncheckedValue),
    (Scopes::Country, "army_manpower_in_state", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "attack_skill_level", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "average_stats", UncheckedValue),
    (Scopes::State.union(Scopes::Country), "building_count_trigger", UncheckedValue),
    (Scopes::PurchaseContract, "buyer", UncheckedValue),
    (Scopes::Country.union(Scopes::Character), "can_be_country_leader", UncheckedValue),
    (Scopes::None, "can_build_railway", UncheckedValue),
    (Scopes::State, "can_construct_building", UncheckedValue),
    (Scopes::Country, "can_declare_war_on", UncheckedValue),
    (Scopes::Country, "can_research", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "can_select_trait", UncheckedValue),
    (Scopes::None, "career_profile_check_medal", UncheckedValue),
    (Scopes::None, "career_profile_check_playthrough_ratio", UncheckedValue),
    (Scopes::None, "career_profile_check_playthrough_value", UncheckedValue),
    (Scopes::None, "career_profile_check_points", UncheckedValue),
    (Scopes::None, "career_profile_check_ratio", UncheckedValue),
    (Scopes::None, "career_profile_check_ribbon", UncheckedValue),
    (Scopes::None, "career_profile_check_value", UncheckedValue),
    (Scopes::None, "career_profile_has_player_flag", UncheckedValue),
    (Scopes::None, "career_profile_set_temp_playthrough_variable", UncheckedValue),
    (Scopes::None, "career_profile_set_temp_variable", UncheckedValue),
    (Scopes::Country, "casualties", UncheckedValue),
    (Scopes::Country, "casualties_inflicted_by", UncheckedValue),
    (Scopes::Country, "casualties_k", UncheckedValue),
    (Scopes::None, "check_variable", UncheckedValue),
    (Scopes::Country, "civilwar_target", UncheckedValue),
    (Scopes::None, "clamp_temp_variable", UncheckedValue),
    (Scopes::None, "clear_temp_array", UncheckedValue),
    (Scopes::Country, "command_power", UncheckedValue),
    (Scopes::Country, "command_power_daily", UncheckedValue),
    (Scopes::Country, "compare_autonomy_progress_ratio", UncheckedValue),
    (Scopes::Country, "compare_autonomy_state", UncheckedValue),
    (Scopes::Country, "compare_intel_with", UncheckedValue),
    (Scopes::State, "compliance", UncheckedValue),
    (Scopes::State, "compliance_speed", UncheckedValue),
    (Scopes::Country, "conscription_ratio", UncheckedValue),
    (Scopes::PurchaseContract, "contract_contains_equipment", UncheckedValue),
    (Scopes::Country, "controls_province", UncheckedValue),
    (Scopes::Country, "controls_state", UncheckedValue),
    (Scopes::Country, "convoy_threat", UncheckedValue),
    (Scopes::Country, "core_compliance", UncheckedValue),
    (Scopes::Country, "core_resistance", UncheckedValue),
    (Scopes::None, "count_triggers", UncheckedValue),
    (Scopes::None, "country_exists", UncheckedValue),
    (Scopes::Country, "current_conscription_amount", UncheckedValue),
    (Scopes::None, "custom_override_tooltip", UncheckedValue),
    (Scopes::None, "custom_trigger_tooltip", UncheckedValue),
    (Scopes::None, "date", UncheckedValue),
    (Scopes::Country, "days_since_capitulated", UncheckedValue),
    (Scopes::State, "days_since_last_strategic_bombing", UncheckedValue),
    (Scopes::PurchaseContract, "deal_completion", UncheckedValue),
    (Scopes::Country, "decryption_progress", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "defense_skill_level", UncheckedValue),
    (Scopes::None, "difficulty", UncheckedValue),
    (Scopes::Combatant, "dig_in", UncheckedValue),
    (Scopes::State, "distance_to", UncheckedValue),
    (Scopes::None, "divide_temp_variable", UncheckedValue),
    (Scopes::Division, "division_has_battalion_in_template", UncheckedValue),
    (Scopes::Division, "division_has_majority_template", UncheckedValue),
    (Scopes::Country, "divisions_in_border_state", UncheckedValue),
    (Scopes::Country, "divisions_in_state", UncheckedValue),
    (Scopes::Country, "enemies_naval_strength_ratio", UncheckedValue),
    (Scopes::Country, "enemies_strength_ratio", UncheckedValue),
    (Scopes::Country, "estimated_intel_max_armor", UncheckedValue),
    (Scopes::Country, "estimated_intel_max_piercing", UncheckedValue),
    (Scopes::Country, "exists", UncheckedValue),
    (Scopes::Combatant, "fastest_unit", UncheckedValue),
    (Scopes::Country, "fighting_army_strength_ratio", UncheckedValue),
    (Scopes::None, "find_highest_in_array", UncheckedValue),
    (Scopes::None, "find_lowest_in_array", UncheckedValue),
    (Scopes::Country, "focus_progress", UncheckedValue),
    (Scopes::Country, "foreign_manpower", UncheckedValue),
    (Scopes::State, "free_building_slots", UncheckedValue),
    (Scopes::Combatant, "frontage_full", UncheckedValue),
    (Scopes::Country, "fuel_ratio", UncheckedValue),
    (Scopes::None, "game_rules_allow_achievements", UncheckedValue),
    (Scopes::Country, "garrison_manpower_need", UncheckedValue),
    (Scopes::Country, "get_highest_scored_country_temp", UncheckedValue),
    (Scopes::Country, "get_sorted_scored_countries_temp", UncheckedValue),
    (Scopes::Country, "get_supply_vehicles_temp", UncheckedValue),
    (Scopes::Country, "gives_military_access_to", UncheckedValue),
    (Scopes::Combatant, "hardness", UncheckedValue),
    (Scopes::Character, "has_ability", UncheckedValue),
    (Scopes::Country, "has_active_mission", UncheckedValue),
    (Scopes::State, "has_active_resistance", UncheckedValue),
    (Scopes::Country, "has_added_tension_amount", UncheckedValue),
    (Scopes::Character, "has_advisor_role", UncheckedValue),
    (Scopes::Country, "has_air_experience", UncheckedValue),
    (Scopes::Character, "has_air_ledger", UncheckedValue),
    (Scopes::Country, "has_allowed_idea_with_traits", UncheckedValue),
    (Scopes::Country, "has_annex_war_goal", UncheckedValue),
    (Scopes::None, "has_any_custom_difficulty_setting", UncheckedValue),
    (Scopes::Country, "has_any_license", UncheckedValue),
    (Scopes::Country, "has_any_power_balance", UncheckedValue),
    (Scopes::Country, "has_army_experience", UncheckedValue),
    (Scopes::Character, "has_army_ledger", UncheckedValue),
    (Scopes::Country, "has_army_manpower", UncheckedValue),
    (Scopes::Country, "has_army_size", UncheckedValue),
    (Scopes::Combatant, "has_artillery_ratio", UncheckedValue),
    (Scopes::Country, "has_attache", UncheckedValue),
    (Scopes::Country, "has_attache_from", UncheckedValue),
    (Scopes::Country, "has_autonomy_state", UncheckedValue),
    (Scopes::Country, "has_available_idea_with_traits", UncheckedValue),
    (Scopes::Country, "has_bombing_war_support", UncheckedValue),
    (Scopes::State.union(Scopes::Country), "has_border_war", UncheckedValue),
    (Scopes::None, "has_border_war_between", UncheckedValue),
    (Scopes::State.union(Scopes::Country), "has_border_war_with", UncheckedValue),
    (Scopes::Country, "has_breakthrough_points", UncheckedValue),
    (Scopes::Country, "has_built", UncheckedValue),
    (Scopes::Country, "has_capitulated", UncheckedValue),
    (Scopes::Country, "has_captured_operative", UncheckedValue),
    (Scopes::Combatant, "has_carrier_airwings_in_own_combat", UncheckedValue),
    (Scopes::Combatant, "has_carrier_airwings_on_mission", UncheckedValue),
    (Scopes::Country, "has_casualties_war_support", UncheckedValue),
    (Scopes::Combatant, "has_cavalry_ratio", UncheckedValue),
    (Scopes::Country, "has_character", UncheckedValue),
    (Scopes::Character, "has_character_flag", UncheckedValue),
    (Scopes::Country, "has_civil_war", UncheckedValue),
    (Scopes::Country, "has_collaboration", UncheckedValue),
    (Scopes::Combatant, "has_combat_modifier", UncheckedValue),
    (Scopes::None, "has_completed_custom_achievement", UncheckedValue),
    (Scopes::Country, "has_completed_focus", UncheckedValue),
    (Scopes::State.union(Scopes::Country), "has_contested_owner", UncheckedValue),
    (Scopes::Country, "has_convoys_war_support", UncheckedValue),
    (Scopes::Country, "has_core_occupation_modifier", UncheckedValue),
    (Scopes::Country, "has_cosmetic_tag", UncheckedValue),
    (Scopes::Country, "has_country_custom_difficulty_setting", UncheckedValue),
    (Scopes::Country, "has_country_flag", UncheckedValue),
    (Scopes::Country, "has_country_leader", UncheckedValue),
    (Scopes::Country, "has_country_leader_ideology", UncheckedValue),
    (Scopes::Country, "has_country_leader_with_trait", UncheckedValue),
    (Scopes::None, "has_custom_difficulty_setting", UncheckedValue),
    (Scopes::Country, "has_damaged_buildings", UncheckedValue),
    (Scopes::Country, "has_decision", UncheckedValue),
    (Scopes::Country, "has_defensive_war", UncheckedValue),
    (Scopes::Country, "has_defensive_war_with", UncheckedValue),
    (Scopes::Country, "has_deployed_air_force_size", UncheckedValue),
    (Scopes::Country, "has_design_based_on", UncheckedValue),
    (Scopes::None, "has_dlc", UncheckedValue),
    (Scopes::Country, "has_done_agency_upgrade", UncheckedValue),
    (
        Scopes::State.union(Scopes::Country).union(Scopes::Character),
        "has_dynamic_modifier",
        UncheckedValue,
    ),
    (Scopes::Country, "has_elections", UncheckedValue),
    (Scopes::Country, "has_equipment", UncheckedValue),
    (Scopes::None, "has_event_target", UncheckedValue),
    (Scopes::Country, "has_facility_specialization", UncheckedValue),
    (Scopes::Country, "has_finished_collecting_for_operation", UncheckedValue),
    (Scopes::Combatant, "has_flanked_opponent", UncheckedValue),
    (Scopes::Country, "has_focus_tree", UncheckedValue),
    (Scopes::Country, "has_fuel", UncheckedValue),
    (Scopes::Country, "has_full_control_of_state", UncheckedValue),
    (Scopes::None, "has_game_rule", UncheckedValue),
    (Scopes::None, "has_global_flag", UncheckedValue),
    (Scopes::Country, "has_government", UncheckedValue),
    (Scopes::Country, "has_guaranteed", UncheckedValue),
    (Scopes::Character, "has_id", UncheckedValue),
    (Scopes::Country, "has_idea", UncheckedValue),
    (Scopes::Country, "has_idea_with_trait", UncheckedValue),
    (Scopes::Character, "has_ideology", UncheckedValue),
    (Scopes::Character, "has_ideology_group", UncheckedValue),
    (Scopes::Country, "has_intelligence_agency", UncheckedValue),
    (Scopes::Country, "has_legitimacy", UncheckedValue),
    (Scopes::Country, "has_license", UncheckedValue),
    (Scopes::Country, "has_manpower", UncheckedValue),
    (Scopes::Country, "has_manpower_for_recruit_change_to", UncheckedValue),
    (Scopes::Country, "has_market_access_with", UncheckedValue),
    (Scopes::Combatant, "has_max_planning", UncheckedValue),
    (Scopes::Country, "has_military_access_to", UncheckedValue),
    (Scopes::Country, "has_military_industrial_organization", UncheckedValue),
    (Scopes::Country, "has_mined", UncheckedValue),
    (Scopes::Country, "has_mines", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_equipment_type", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_flag", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_number_of_completed_traits", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_policy", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_policy_active", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_research_category", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_size", UncheckedValue),
    (Scopes::IndustrialOrg, "has_mio_trait", UncheckedValue),
    (Scopes::Character, "has_nationality", UncheckedValue),
    (Scopes::Country, "has_naval_invasion_against_state", UncheckedValue),
    (Scopes::Country, "has_navy_experience", UncheckedValue),
    (Scopes::Character, "has_navy_ledger", UncheckedValue),
    (Scopes::Country, "has_navy_size", UncheckedValue),
    (Scopes::Country, "has_non_aggression_pact_with", UncheckedValue),
    (Scopes::State, "has_occupation_modifier", UncheckedValue),
    (Scopes::Country, "has_offensive_war", UncheckedValue),
    (Scopes::Country, "has_offensive_war_with", UncheckedValue),
    (Scopes::Division, "has_officer_name", UncheckedValue),
    (Scopes::Country, "has_operation_token", UncheckedValue),
    (Scopes::Country, "has_opinion", UncheckedValue),
    (Scopes::Country, "has_opinion_modifier", UncheckedValue),
    (Scopes::Country, "has_political_power", UncheckedValue),
    (Scopes::Country, "has_power_balance", UncheckedValue),
    (Scopes::None, "has_power_balance_modifier", UncheckedValue),
    (Scopes::SpecialProject, "has_project_flag", UncheckedValue),
    (Scopes::None, "has_railway_connection", UncheckedValue),
    (Scopes::None, "has_railway_level", UncheckedValue),
    (Scopes::Country, "has_relation_modifier", UncheckedValue),
    (Scopes::Combatant, "has_reserves", UncheckedValue),
    (Scopes::State, "has_resistance", UncheckedValue),
    (Scopes::State, "has_resources_amount", UncheckedValue),
    (Scopes::Country, "has_resources_in_country", UncheckedValue),
    (Scopes::State.union(Scopes::Country), "has_resources_rights", UncheckedValue),
    (Scopes::None, "has_rule", UncheckedValue),
    (Scopes::Character, "has_scientist_level", UncheckedValue),
    (Scopes::Country, "has_scientist_specialization", UncheckedValue),
    (Scopes::Country, "has_shine_effect_on_focus", UncheckedValue),
    (Scopes::Country, "has_stability", UncheckedValue),
    (Scopes::None, "has_start_date", UncheckedValue),
    (Scopes::State, "has_state_category", UncheckedValue),
    (Scopes::State, "has_state_flag", UncheckedValue),
    (Scopes::Country, "has_subject", UncheckedValue),
    (Scopes::Country, "has_tech", UncheckedValue),
    (Scopes::Country, "has_tech_bonus", UncheckedValue),
    (Scopes::Country, "has_template", UncheckedValue),
    (Scopes::Country, "has_template_ai_majority_unit", UncheckedValue),
    (Scopes::Country, "has_template_containing_unit", UncheckedValue),
    (Scopes::Country, "has_template_majority_unit", UncheckedValue),
    (Scopes::Country, "has_terrain", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "has_trait", UncheckedValue),
    (Scopes::Country, "has_truce_with", UncheckedValue),
    (Scopes::Country, "has_unit_leader", UncheckedValue),
    (Scopes::Character, "has_unit_leader_flag", UncheckedValue),
    (Scopes::Combatant, "has_unit_type", UncheckedValue),
    (Scopes::None, "has_variable", UncheckedValue),
    (Scopes::Country, "has_volunteers_amount_from", UncheckedValue),
    (Scopes::Country, "has_war", UncheckedValue),
    (Scopes::Country, "has_war_support", UncheckedValue),
    (Scopes::Country, "has_war_together_with", UncheckedValue),
    (Scopes::Country, "has_war_with", UncheckedValue),
    (Scopes::Country, "has_war_with_major", UncheckedValue),
    (Scopes::Country, "has_war_with_wargoal_against", UncheckedValue),
    (Scopes::Country, "has_wargoal_against", UncheckedValue),
    (
        Scopes::State
            .union(Scopes::Country)
            .union(Scopes::Character)
            .union(Scopes::Combatant)
            .union(Scopes::Ace)
            .union(Scopes::StrategicRegion)
            .union(Scopes::Operation)
            .union(Scopes::IndustrialOrg)
            .union(Scopes::PurchaseContract)
            .union(Scopes::RaidInstance)
            .union(Scopes::SpecialProject),
        "hidden_trigger",
        UncheckedValue,
    ),
    (Scopes::Country, "ic_ratio", UncheckedValue),
    (Scopes::Country, "ideology_support_trigger", UncheckedValue),
    (Scopes::None, "if", UncheckedValue),
    (Scopes::State, "impassable", UncheckedValue),
    (Scopes::Country, "intel_level_over", UncheckedValue),
    (Scopes::Country, "is_active_decryption_bonuses_enabled", UncheckedValue),
    (Scopes::Character, "is_active_scientist", UncheckedValue),
    (Scopes::Character, "is_advisor", UncheckedValue),
    (Scopes::Country, "is_ai", UncheckedValue),
    (Scopes::Character, "is_air_chief", UncheckedValue),
    (Scopes::Country, "is_ally_with", UncheckedValue),
    (Scopes::Combatant, "is_amphibious_invasion", UncheckedValue),
    (Scopes::Character, "is_army_chief", UncheckedValue),
    (Scopes::Character, "is_army_leader", UncheckedValue),
    (Scopes::Character, "is_assigned", UncheckedValue),
    (Scopes::Combatant, "is_attacker", UncheckedValue),
    (Scopes::State, "is_border_conflict", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "is_border_war", UncheckedValue),
    (Scopes::State, "is_capital", UncheckedValue),
    (Scopes::Character, "is_character", UncheckedValue),
    (Scopes::Character, "is_character_slot", UncheckedValue),
    (Scopes::State, "is_claimed_by", UncheckedValue),
    (Scopes::State, "is_coastal", UncheckedValue),
    (Scopes::State, "is_controlled_by", UncheckedValue),
    (Scopes::State, "is_core_of", UncheckedValue),
    (Scopes::Character, "is_corps_commander", UncheckedValue),
    (Scopes::Character, "is_country_leader", UncheckedValue),
    (Scopes::Country, "is_cryptology_department_active", UncheckedValue),
    (Scopes::None, "is_debug", UncheckedValue),
    (Scopes::Country, "is_decrypting", UncheckedValue),
    (Scopes::Combatant, "is_defender", UncheckedValue),
    (Scopes::State, "is_demilitarized_zone", UncheckedValue),
    (Scopes::Country, "is_dynamic_country", UncheckedValue),
    (Scopes::Country, "is_embargoed_by", UncheckedValue),
    (Scopes::Country, "is_embargoing", UncheckedValue),
    (Scopes::Country, "is_exile_host", UncheckedValue),
    (Scopes::Country, "is_exiled_in", UncheckedValue),
    (Scopes::Character, "is_exiled_leader", UncheckedValue),
    (Scopes::Character, "is_exiled_leader_from", UncheckedValue),
    (Scopes::Country, "is_faction_leader", UncheckedValue),
    (Scopes::Country.union(Scopes::Character).union(Scopes::Ace), "is_female", UncheckedValue),
    (Scopes::Character, "is_field_marshal", UncheckedValue),
    (Scopes::Combatant, "is_fighting_air_units", UncheckedValue),
    (Scopes::Combatant, "is_fighting_in_terrain", UncheckedValue),
    (Scopes::Combatant, "is_fighting_in_weather", UncheckedValue),
    (Scopes::State, "is_fully_controlled_by", UncheckedValue),
    (Scopes::Country, "is_fully_decrypted", UncheckedValue),
    (Scopes::Country, "is_government_in_exile", UncheckedValue),
    (Scopes::Country, "is_guaranteed_by", UncheckedValue),
    (Scopes::Character, "is_high_command", UncheckedValue),
    (Scopes::Character, "is_hired_as_advisor", UncheckedValue),
    (Scopes::None, "is_historical_focus_on", UncheckedValue),
    (Scopes::Country, "is_hosting_exile", UncheckedValue),
    (Scopes::None, "is_in_array", UncheckedValue),
    (Scopes::Country, "is_in_faction", UncheckedValue),
    (Scopes::Country, "is_in_faction_with", UncheckedValue),
    (Scopes::State, "is_in_home_area", UncheckedValue),
    (Scopes::Country, "is_in_peace_conference", UncheckedValue),
    (Scopes::Country, "is_in_tech_sharing_group", UncheckedValue),
    (Scopes::None, "is_ironman", UncheckedValue),
    (Scopes::State, "is_island_state", UncheckedValue),
    (Scopes::Country, "is_justifying_wargoal_against", UncheckedValue),
    (Scopes::Character, "is_leading_army", UncheckedValue),
    (Scopes::Character, "is_leading_army_group", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "is_leading_volunteer_group", UncheckedValue),
    (
        Scopes::Character.union(Scopes::Combatant),
        "is_leading_volunteer_group_with_original_country",
        UncheckedValue,
    ),
    (Scopes::Country, "is_lend_leasing", UncheckedValue),
    (Scopes::Country, "is_licensing_any_to", UncheckedValue),
    (Scopes::Country, "is_licensing_to", UncheckedValue),
    (Scopes::Country, "is_major", UncheckedValue),
    (Scopes::IndustrialOrg, "is_military_industrial_organization", UncheckedValue),
    (Scopes::IndustrialOrg, "is_mio_assigned_to_task", UncheckedValue),
    (Scopes::IndustrialOrg, "is_mio_available", UncheckedValue),
    (Scopes::IndustrialOrg, "is_mio_trait_available", UncheckedValue),
    (Scopes::IndustrialOrg, "is_mio_trait_completed", UncheckedValue),
    (Scopes::IndustrialOrg, "is_mio_visible", UncheckedValue),
    (Scopes::Character, "is_navy_chief", UncheckedValue),
    (Scopes::Character, "is_navy_leader", UncheckedValue),
    (Scopes::Country, "is_neighbor_of", UncheckedValue),
    (Scopes::State, "is_on_continent", UncheckedValue),
    (Scopes::State, "is_one_state_island", UncheckedValue),
    (Scopes::Operation, "is_operation_type", UncheckedValue),
    (Scopes::Character, "is_operative", UncheckedValue),
    (Scopes::Character, "is_operative_captured", UncheckedValue),
    (Scopes::State, "is_owned_and_controlled_by", UncheckedValue),
    (Scopes::State, "is_owned_by", UncheckedValue),
    (Scopes::Country, "is_owner_neighbor_of", UncheckedValue),
    (Scopes::Character, "is_political_advisor", UncheckedValue),
    (Scopes::None, "is_power_balance_in_range", UncheckedValue),
    (Scopes::None, "is_power_balance_side_active", UncheckedValue),
    (Scopes::Country, "is_preparing_operation", UncheckedValue),
    (Scopes::Country, "is_puppet", UncheckedValue),
    (Scopes::Country, "is_puppet_of", UncheckedValue),
    (Scopes::Country, "is_researching_technology", UncheckedValue),
    (Scopes::Country, "is_running_operation", UncheckedValue),
    (Scopes::Character, "is_scientist_injured", UncheckedValue),
    (Scopes::Country, "is_special_project_being_researched", UncheckedValue),
    (Scopes::Country, "is_special_project_completed", UncheckedValue),
    (Scopes::Country, "is_spymaster", UncheckedValue),
    (Scopes::Country, "is_staging_coup", UncheckedValue),
    (Scopes::Country, "is_subject", UncheckedValue),
    (Scopes::Country, "is_subject_of", UncheckedValue),
    (Scopes::Country, "is_target_of_coup", UncheckedValue),
    (Scopes::Character, "is_theorist", UncheckedValue),
    (Scopes::None, "is_tutorial", UncheckedValue),
    (Scopes::Character, "is_unit_leader", UncheckedValue),
    (Scopes::Division, "is_unit_template_reserves", UncheckedValue),
    (Scopes::Combatant, "is_winning", UncheckedValue),
    (Scopes::Country, "land_doctrine_level", UncheckedValue),
    (Scopes::Combatant, "less_combat_width_than_opponent", UncheckedValue),
    (Scopes::None, "log", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "logistics_skill_level", UncheckedValue),
    (Scopes::Country, "longest_war_length", UncheckedValue),
    (Scopes::Country, "manpower_per_military_factory", UncheckedValue),
    (
        Scopes::State
            .union(Scopes::Country)
            .union(Scopes::Character)
            .union(Scopes::Combatant)
            .union(Scopes::Ace)
            .union(Scopes::StrategicRegion)
            .union(Scopes::Operation)
            .union(Scopes::IndustrialOrg)
            .union(Scopes::PurchaseContract)
            .union(Scopes::RaidInstance)
            .union(Scopes::SpecialProject),
        "meta_trigger",
        UncheckedValue,
    ),
    (Scopes::Combatant, "min_planning", UncheckedValue),
    (Scopes::Country, "mine_threat", UncheckedValue),
    (Scopes::None, "modulo_temp_variable", UncheckedValue),
    (Scopes::None, "multiply_temp_variable", UncheckedValue),
    (Scopes::Country, "naval_strength_comparison", UncheckedValue),
    (Scopes::Country, "naval_strength_ratio", UncheckedValue),
    (Scopes::Country, "network_national_coverage", UncheckedValue),
    (Scopes::Country, "network_strength", UncheckedValue),
    (Scopes::Combatant, "night", UncheckedValue),
    (Scopes::State, "non_damaged_building_level", UncheckedValue),
    (Scopes::None, "not", UncheckedValue),
    (Scopes::Character, "not_already_hired_except_as", UncheckedValue),
    (Scopes::Country, "num_battalions_in_states", UncheckedValue),
    (Scopes::Country, "num_divisions", UncheckedValue),
    (Scopes::Country, "num_divisions_in_states", UncheckedValue),
    (Scopes::Country, "num_faction_members", UncheckedValue),
    (Scopes::Country, "num_fake_intel_divisions", UncheckedValue),
    (Scopes::Country, "num_finished_operations", UncheckedValue),
    (Scopes::Country, "num_free_operative_slots", UncheckedValue),
    (Scopes::Country, "num_nukes_being_dropped", UncheckedValue),
    (Scopes::Country, "num_nukes_left_to_drop", UncheckedValue),
    (Scopes::Country, "num_occupied_states", UncheckedValue),
    (Scopes::Country, "num_of_available_civilian_factories", UncheckedValue),
    (Scopes::Country, "num_of_available_military_factories", UncheckedValue),
    (Scopes::Country, "num_of_available_naval_factories", UncheckedValue),
    (Scopes::None, "num_of_career_profile_points", UncheckedValue),
    (Scopes::Country, "num_of_civilian_factories", UncheckedValue),
    (Scopes::Country, "num_of_civilian_factories_available_for_projects", UncheckedValue),
    (Scopes::Country, "num_of_controlled_factories", UncheckedValue),
    (Scopes::Country, "num_of_controlled_states", UncheckedValue),
    (Scopes::Country, "num_of_factories", UncheckedValue),
    (Scopes::Country, "num_of_military_factories", UncheckedValue),
    (Scopes::Country, "num_of_naval_factories", UncheckedValue),
    (Scopes::Country, "num_of_nukes", UncheckedValue),
    (Scopes::Country, "num_of_operatives", UncheckedValue),
    (Scopes::Country, "num_of_owned_factories", UncheckedValue),
    (Scopes::Country, "num_of_supply_nodes", UncheckedValue),
    (Scopes::Country, "num_operative_slots", UncheckedValue),
    (Scopes::State, "num_owned_neighbour_states", UncheckedValue),
    (Scopes::Country, "num_planes_stationed_in_regions", UncheckedValue),
    (Scopes::Country, "num_researched_technologies", UncheckedValue),
    (Scopes::Country, "num_subjects", UncheckedValue),
    (Scopes::Country, "num_tech_sharing_groups", UncheckedValue),
    (Scopes::Character, "num_units", UncheckedValue),
    (Scopes::State.union(Scopes::Country), "occupation_law", UncheckedValue),
    (Scopes::State, "occupied_country_tag", UncheckedValue),
    (Scopes::Character, "operative_leader_mission", UncheckedValue),
    (Scopes::Character, "operative_leader_operation", UncheckedValue),
    (Scopes::None, "or", UncheckedValue),
    (Scopes::Country, "original_research_slots", UncheckedValue),
    (Scopes::Country, "original_tag", UncheckedValue),
    (Scopes::Country, "owns_any_state_of", UncheckedValue),
    (Scopes::Country, "owns_state", UncheckedValue),
    (Scopes::Country, "pc_current_score", UncheckedValue),
    (Scopes::State, "pc_does_state_stack_demilitarized", UncheckedValue),
    (Scopes::State, "pc_does_state_stack_dismantled", UncheckedValue),
    (Scopes::Country, "pc_is_forced_government", UncheckedValue),
    (Scopes::Country, "pc_is_forced_government_by", UncheckedValue),
    (Scopes::Country, "pc_is_forced_government_to", UncheckedValue),
    (Scopes::Country, "pc_is_liberated", UncheckedValue),
    (Scopes::Country, "pc_is_loser", UncheckedValue),
    (Scopes::Country, "pc_is_on_same_side_as", UncheckedValue),
    (Scopes::Country, "pc_is_on_winning_side", UncheckedValue),
    (Scopes::Country, "pc_is_puppeted", UncheckedValue),
    (Scopes::Country, "pc_is_puppeted_by", UncheckedValue),
    (Scopes::State, "pc_is_state_claimed", UncheckedValue),
    (Scopes::State, "pc_is_state_claimed_and_taken_by", UncheckedValue),
    (Scopes::State, "pc_is_state_claimed_by", UncheckedValue),
    (Scopes::State, "pc_is_state_outside_influence_for_winner", UncheckedValue),
    (Scopes::Country, "pc_is_winner", UncheckedValue),
    (Scopes::Country, "pc_total_score", UncheckedValue),
    (Scopes::None, "pc_turn", UncheckedValue),
    (Scopes::Combatant, "phase", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "planning_skill_level", UncheckedValue),
    (Scopes::Country, "political_power_daily", UncheckedValue),
    (Scopes::Country, "political_power_growth", UncheckedValue),
    (Scopes::None, "power_balance_daily_change", UncheckedValue),
    (Scopes::None, "power_balance_value", UncheckedValue),
    (Scopes::None, "power_balance_weekly_change", UncheckedValue),
    (Scopes::None, "print_variables", UncheckedValue),
    (Scopes::Combatant, "province_vp", UncheckedValue),
    (Scopes::Country, "received_expeditionary_forces", UncheckedValue),
    (Scopes::Combatant, "recon_advantage", UncheckedValue),
    (Scopes::State, "region", UncheckedValue),
    (Scopes::None, "remove_from_temp_array", UncheckedValue),
    (Scopes::Combatant, "reserves", UncheckedValue),
    (Scopes::State, "resistance", UncheckedValue),
    (Scopes::State, "resistance_speed", UncheckedValue),
    (Scopes::State, "resistance_target", UncheckedValue),
    (Scopes::None, "resize_temp_array", UncheckedValue),
    (Scopes::State.union(Scopes::Country), "resource_count_trigger", UncheckedValue),
    (Scopes::None, "round_temp_variable", UncheckedValue),
    (Scopes::None, "scope_exists", UncheckedValue),
    (Scopes::PurchaseContract, "seller", UncheckedValue),
    (Scopes::None, "set_temp_variable", UncheckedValue),
    (Scopes::None, "set_temp_variable_to_random", UncheckedValue),
    (Scopes::Country, "ships_in_area", UncheckedValue),
    (Scopes::Country, "ships_in_state_ports", UncheckedValue),
    (Scopes::Character.union(Scopes::Combatant), "skill", UncheckedValue),
    (Scopes::Combatant, "skill_advantage", UncheckedValue),
    (Scopes::State, "state", UncheckedValue),
    (Scopes::State, "state_and_terrain_strategic_value", UncheckedValue),
    (Scopes::State, "state_population", UncheckedValue),
    (Scopes::State, "state_population_k", UncheckedValue),
    (Scopes::State, "state_strategic_value", UncheckedValue),
    (Scopes::Country, "stockpile_ratio", UncheckedValue),
    (Scopes::Country, "strength_ratio", UncheckedValue),
    (Scopes::None, "subtract_from_temp_variable", UncheckedValue),
    (Scopes::Country, "surrender_progress", UncheckedValue),
    (Scopes::Country.union(Scopes::Combatant), "tag", UncheckedValue),
    (Scopes::Country, "target_conscription_amount", UncheckedValue),
    (Scopes::Combatant, "temperature", UncheckedValue),
    (Scopes::None, "threat", UncheckedValue),
    (Scopes::Division, "unit_organization", UncheckedValue),
    (Scopes::Division, "unit_strength", UncheckedValue),
    (Scopes::Country, "war_length_with", UncheckedValue),
];
