&[
    ("Abs_CFixedPoint", Args::Args(&[DType(CFixedPoint)]), CFixedPoint),
    ("Abs_float", Args::Args(&[DType(float)]), float),
    ("Abs_int32", Args::Args(&[DType(int32)]), int32),
    ("Abs_int64", Args::Args(&[DType(int64)]), int64),
    ("AccessConstructionSpeeds", Args::Args(&[]), Unknown),
    ("AccessMapEditorLayerBorders", Args::Args(&[]), Unknown),
    ("AccessMetaPlayer", Args::Args(&[]), Unknown),
    ("AccessPlayer", Args::Args(&[]), Unknown),
    ("AddLocalizationIf", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("AddTextIf", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("Add_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Add_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Add_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Add_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Add_int64", Args::Args(&[DType(int64), DType(int64)]), int64),
    ("Add_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("Add_uint64", Args::Args(&[DType(uint64), DType(uint64)]), uint64),
    ("And", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("AreAchievementsAvailable", Args::Args(&[]), bool),
    ("BindFoldOutContext", Args::Args(&[]), void),
    ("BoolTo1And2", Args::Args(&[DType(Unknown)]), int32),
    ("BoolTo2And1", Args::Args(&[DType(Unknown)]), int32),
    ("CalcDynTrendLatestDate", Args::Args(&[DType(Unknown)]), CString),
    ("CalcDynTrendOldestDate", Args::Args(&[DType(Unknown)]), CString),
    ("CanEditSettingsAfterHost", Args::Args(&[]), bool),
    ("CanGetAchievements", Args::Args(&[]), bool),
    ("CanOpenLobby", Args::Args(&[]), bool),
    ("CanOpenRightClickContextMenu", Args::Args(&[]), bool),
    ("ChangeAllConstructionSpeed", Args::Args(&[DType(Unknown)]), Vic3(Command)),
    ("ChangeAllConstructionSpeedTooltip", Args::Args(&[DType(Unknown)]), CString),
    ("ClearDynamicTerrainOverrideForAllProvinces", Args::Args(&[]), void),
    ("ClearHostError", Args::Args(&[]), void),
    ("CloseAllTooltips", Args::Args(&[]), void),
    ("ConcatIfNeitherEmpty", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("Concatenate", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("Concept", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("CopyBuildVersionInfoToClipboard", Args::Args(&[]), void),
    ("CopyServerID", Args::Args(&[]), void),
    ("CurrentAndMaxToProgressbarValueInt32", Args::Args(&[DType(Unknown), DType(Unknown)]), float),
    ("DataModelFirst", Args::Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelHasItems", Args::Args(&[DType(Unknown)]), bool),
    ("DataModelLast", Args::Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelRepeatedItem", Args::Args(&[DType(Unknown)]), Unknown),
    ("DataModelSkipFirst", Args::Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelSkipLast", Args::Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelSubSpan", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("DebugGetMapMode", Args::Args(&[]), CString),
    ("DoubleToFloat", Args::Args(&[DType(Unknown)]), float),
    ("EqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("EqualTo_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), bool),
    ("EqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("EqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("EqualTo_int64", Args::Args(&[DType(int64), DType(int64)]), bool),
    ("EqualTo_string", Args::Args(&[DType(CString), DType(CString)]), bool),
    ("EqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("EqualTo_uint64", Args::Args(&[DType(uint64), DType(uint64)]), bool),
    ("Execute", Args::Args(&[DType(Unknown)]), void),
    ("ExecuteConsoleCommand", Args::Args(&[DType(Unknown)]), void),
    ("ExecuteConsoleCommands", Args::Args(&[DType(Unknown)]), void),
    ("ExecuteConsoleCommandsForced", Args::Args(&[DType(Unknown)]), void),
    ("FixedPointToFloat", Args::Args(&[DType(Unknown)]), float),
    ("FixedPointToInt", Args::Args(&[DType(Unknown)]), int32),
    ("FixedPointToProgressbarValue", Args::Args(&[DType(Unknown)]), float),
    ("FocusCameraOnCityOutOfState", Args::Args(&[]), void),
    ("GameHasMultiplePlayers", Args::Args(&[]), bool),
    ("GameIsMultiplayer", Args::Args(&[]), bool),
    ("GetAchievementsAvailableString", Args::Args(&[]), CString),
    ("GetApprovalRatingFromValue", Args::Args(&[DType(Unknown)]), CString),
    ("GetArrowIcon_CFixedPoint", Args::Args(&[DType(Unknown)]), CString),
    ("GetArrowIcon_int32", Args::Args(&[DType(Unknown)]), CString),
    ("GetArrowIcon_int64", Args::Args(&[DType(Unknown)]), CString),
    ("GetAutosaveName", Args::Args(&[]), CString),
    ("GetBattleCondition", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetBuildVersionDescriptionWithClickToCopy", Args::Args(&[]), CString),
    ("GetBuildingType", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetCanGoToFrontend", Args::Args(&[]), bool),
    ("GetCanGoToFrontendDesc", Args::Args(&[]), CString),
    ("GetConfirmationDesc", Args::Args(&[DType(Unknown)]), CString),
    ("GetConstructionSectorType", Args::Args(&[]), Unknown),
    ("GetCurrentFps", Args::Args(&[]), float),
    ("GetCurrentLoadingScreen", Args::Args(&[]), Unknown),
    ("GetDataModelSize", Args::Args(&[DType(Unknown)]), int32),
    ("GetDecreeType", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetDefaultServerName", Args::Args(&[]), CUTF8String),
    ("GetDefine", Args::Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("GetDefineAtIndex", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetDesc", Args::Args(&[DType(Unknown)]), CString),
    ("GetDescriptiveText", Args::Args(&[DType(Unknown)]), CString),
    ("GetDiplomaticActionType", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetDiplomaticPlayType", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetDlcCollection", Args::Args(&[]), Unknown),
    ("GetDynTrendMax", Args::Args(&[DType(Unknown)]), CFixedPoint),
    ("GetDynTrendMin", Args::Args(&[DType(Unknown)]), CFixedPoint),
    ("GetDynTrendPlotPoints", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetEnumIndex", Args::Args(&[DType(Unknown)]), CVector2i),
    ("GetEthnicities", Args::Args(&[]), Unknown),
    ("GetGameVersionDisplay", Args::Args(&[]), CString),
    ("GetGameVersionInfo", Args::Args(&[]), CString),
    ("GetGameVersionInfoShort", Args::Args(&[]), CString),
    ("GetGlobalList", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetGlobalMaxLandDefense", Args::Args(&[]), CFixedPoint),
    ("GetGlobalMaxLandOffense", Args::Args(&[]), CFixedPoint),
    ("GetGlobalMaxNavalDefense", Args::Args(&[]), CFixedPoint),
    ("GetGlobalMaxNavalOffense", Args::Args(&[]), CFixedPoint),
    ("GetGlobalVariable", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetGoods", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetGuiPositionFromPercentCoordinates", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetHostError", Args::Args(&[]), CUTF8String),
    ("GetIdeology", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetInstitutionType", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetInteger", Args::Args(&[DType(Unknown)]), int32),
    ("GetInterestGroupVariant", Args::Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("GetInterestingCountrySettings", Args::Args(&[]), Unknown),
    ("GetInvParentScale", Args::Args(&[DType(Unknown)]), float),
    ("GetIsChecked", Args::Args(&[DType(Unknown)]), bool),
    ("GetLargeFlagFrameSize", Args::Args(&[]), CVector2i),
    ("GetLatestDate", Args::Args(&[DType(Unknown)]), CString),
    ("GetLawGroup", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetLawType", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetLegitimacyLevel", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetLegitimacyLevels", Args::Args(&[]), Unknown),
    ("GetLensToolbar", Args::Args(&[]), Unknown),
    ("GetLoadingScreenManager", Args::Args(&[]), Unknown),
    ("GetLocalizedDefine", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetLocalizedDefineAtIndex", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("GetLoyaltyTypes", Args::Args(&[]), Unknown),
    ("GetMPChecksum", Args::Args(&[]), CString),
    ("GetManpowerColorVec", Args::Args(&[DType(Unknown)]), CVector4f),
    ("GetMapModeIndices", Args::Args(&[]), Unknown),
    ("GetMapModeName", Args::Args(&[DType(Unknown)]), CString),
    ("GetMax", Args::Args(&[DType(Unknown)]), CFixedPoint),
    ("GetMediumFlagFrameSize", Args::Args(&[]), CVector2i),
    ("GetMetaPlayer", Args::Args(&[]), Unknown),
    ("GetMin", Args::Args(&[DType(Unknown)]), CFixedPoint),
    ("GetMoraleColorString", Args::Args(&[DType(Unknown)]), CString),
    ("GetMoraleColorVec", Args::Args(&[DType(Unknown)]), CVector4f),
    ("GetNullProperty", Args::Args(&[]), Unknown),
    ("GetNumberAbove_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("GetOldestDate", Args::Args(&[DType(Unknown)]), CString),
    ("GetOpenLobbyTooltip", Args::Args(&[]), CString),
    ("GetPlayer", Args::Args(&[]), Vic3(Country)),
    ("GetPlayersCount", Args::Args(&[]), int32),
    ("GetPopType", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetPopTypesInLowerStrataDesc", Args::Args(&[]), CString),
    ("GetPopTypesInMiddleStrataDesc", Args::Args(&[]), CString),
    ("GetPopTypesInUpperStrataDesc", Args::Args(&[]), CString),
    ("GetPortraitTextureFromDna", Args::Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("GetPrevTrendValue", Args::Args(&[DType(Unknown)]), CFixedPoint),
    ("GetPrevTrendValueFor", Args::Args(&[DType(Unknown), DType(Unknown)]), CFixedPoint),
    ("GetRandomLogInfo", Args::Args(&[]), CString),
    ("GetRankModifier", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetRawTextTooltipTag", Args::Args(&[DType(Unknown)]), CString),
    ("GetRawTrendPlotRectWithFixedY", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Vic3(CPdxFloatRect)),
    ("GetResolutionWithAspectRatio", Args::Args(&[]), CVector2f),
    ("GetSelectedMapMode", Args::Args(&[]), CVector2i),
    ("GetSelectedMapModeName", Args::Args(&[]), CString),
    ("GetSmallFlagFrameSize", Args::Args(&[]), CVector2i),
    ("GetSmartBrushInterpolationNames", Args::Args(&[]), Unknown),
    ("GetSmartBrushPatternNames", Args::Args(&[]), Unknown),
    ("GetStaticModifier", Args::Args(&[IType(Item::Modifier)]), Unknown),
    ("GetStringSettingText", Args::Args(&[DType(Unknown)]), CString),
    ("GetString_CPdxFloatRect", Args::Args(&[DType(Vic3(CPdxFloatRect))]), CString),
    ("GetString_CPdxIntRect", Args::Args(&[DType(Vic3(CPdxIntRect))]), CString),
    ("GetString_CVector2f", Args::Args(&[DType(CVector2f)]), CString),
    ("GetString_CVector2i", Args::Args(&[DType(CVector2i)]), CString),
    ("GetString_CVector3f", Args::Args(&[DType(CVector3f)]), CString),
    ("GetString_CVector3i", Args::Args(&[DType(CVector3i)]), CString),
    ("GetString_CVector4f", Args::Args(&[DType(CVector4f)]), CString),
    ("GetString_CVector4i", Args::Args(&[DType(CVector4i)]), CString),
    ("GetSupplyNetworkColorstring", Args::Args(&[DType(Unknown)]), CString),
    ("GetTrendIcon", Args::Args(&[DType(Unknown)]), CString),
    ("GetTrendIconFor", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetTrendPlotPoints", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetTrendPlotPointsAbsolute", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetTrendPlotPointsNormalized", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetTrendValue", Args::Args(&[DType(Unknown)]), CFixedPoint),
    ("GetTrendValueFor", Args::Args(&[DType(Unknown), DType(Unknown)]), CFixedPoint),
    ("GetUnitStrengthHeader", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("GetUnitStrengthHeaderNoIcon", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetVarTimeRemaining", Args::Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("GfxGetSkins", Args::Args(&[]), Unknown),
    ("GfxSetActiveSkin", Args::Args(&[DType(Unknown)]), void),
    ("GfxSkinIsActive", Args::Args(&[DType(Unknown)]), bool),
    ("GoToFrontend", Args::Args(&[]), void),
    ("GreaterThanOrEqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("GreaterThanOrEqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("GreaterThanOrEqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("GreaterThanOrEqualTo_int64", Args::Args(&[DType(int64), DType(int64)]), bool),
    ("GreaterThanOrEqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("GreaterThanOrEqualTo_uint64", Args::Args(&[DType(uint64), DType(uint64)]), bool),
    ("GreaterThan_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("GreaterThan_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("GreaterThan_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("GreaterThan_int64", Args::Args(&[DType(int64), DType(int64)]), bool),
    ("GreaterThan_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("GreaterThan_uint64", Args::Args(&[DType(uint64), DType(uint64)]), bool),
    ("HasAnyAvailableNewThemes", Args::Args(&[]), bool),
    ("HasAnySelections", Args::Args(&[DType(Unknown)]), bool),
    ("HasAnyThemeIssues", Args::Args(&[]), bool),
    ("HasCitiesOutOfState", Args::Args(&[]), bool),
    ("HasDlcFeature", Args::Args(&[DType(Unknown)]), bool),
    ("HasGameStartedForTheFirstTime", Args::Args(&[]), bool),
    ("HasGameState", Args::Args(&[]), bool),
    ("HasHostError", Args::Args(&[]), bool),
    ("InDebugMode", Args::Args(&[]), bool),
    ("InReleaseMode", Args::Args(&[]), bool),
    ("IntToFixedPoint", Args::Args(&[DType(Unknown)]), CFixedPoint),
    ("IntToFloat", Args::Args(&[DType(Unknown)]), float),
    ("IntToFrameIndex", Args::Args(&[DType(Unknown)]), int32),
    ("IntToUnsigned", Args::Args(&[DType(Unknown)]), uint32),
    ("IsCameraRestrictionsEnabled", Args::Args(&[]), bool),
    ("IsCurrentProductionMethod", Args::Args(&[DType(Unknown)]), bool),
    ("IsDataModelEmpty", Args::Args(&[DType(Unknown)]), bool),
    ("IsDrawCityDebugGrid", Args::Args(&[]), bool),
    ("IsDrawCityDebugSpheres", Args::Args(&[]), bool),
    ("IsDynTrendEmpty", Args::Args(&[DType(Unknown)]), bool),
    ("IsDynamicTerrainAutoUpdate", Args::Args(&[]), bool),
    ("IsDynamicsEnabled", Args::Args(&[]), bool),
    ("IsEmpty", Args::Args(&[DType(Unknown)]), bool),
    ("IsGameChecksumOk", Args::Args(&[]), bool),
    ("IsGameOverScreenShown", Args::Args(&[]), bool),
    ("IsGamePaused", Args::Args(&[]), bool),
    ("IsHost", Args::Args(&[]), bool),
    ("IsInGame", Args::Args(&[]), bool),
    ("IsIronmanEnabled", Args::Args(&[]), bool),
    ("IsLoadedFromSave", Args::Args(&[]), bool),
    ("IsMapModeForced", Args::Args(&[]), bool),
    ("IsMapModeSelected", Args::Args(&[DType(Unknown)]), bool),
    ("IsObserver", Args::Args(&[]), bool),
    ("IsPauseMenuShown", Args::Args(&[]), bool),
    ("IsPlayerInLeft", Args::Args(&[DType(Unknown)]), bool),
    ("IsPotential", Args::Args(&[DType(Unknown)]), bool),
    ("IsPreparationLobby", Args::Args(&[]), bool),
    ("IsSaving", Args::Args(&[]), bool),
    ("IsTerrainManipulatorProvincesPreview", Args::Args(&[]), bool),
    ("IsTutorialLessonActive", Args::Args(&[DType(Unknown)]), bool),
    ("IsValid", Args::Args(&[DType(Unknown)]), bool),
    ("IsZoomLevelFar", Args::Args(&[]), bool),
    ("IsZoomLevelMid", Args::Args(&[]), bool),
    ("IsZoomLevelNear", Args::Args(&[]), bool),
    ("JoinText", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("JominiAccessPlayerJoinRequests", Args::Args(&[]), Unknown),
    ("JominiAreAchievementsAvailable", Args::Args(&[]), bool),
    ("JominiGetAchievementsNotAvailableString", Args::Args(&[]), CString),
    ("JominiGetMultiplayerAccessibleString", Args::Args(&[]), CString),
    ("JominiHasPlayerJoinRequests", Args::Args(&[]), bool),
    ("JominiIsHostOrLocal", Args::Args(&[]), bool),
    ("JominiIsMultiplayerAccessible", Args::Args(&[]), bool),
    ("JominiMultiplayerIsCrossplayEnabled", Args::Args(&[]), bool),
    ("JominiMultiplayerIsCrossplayFilterAvailable", Args::Args(&[]), bool),
    ("JominiPlayer", Args::Args(&[]), Unknown),
    ("LessThanOrEqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("LessThanOrEqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("LessThanOrEqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("LessThanOrEqualTo_int64", Args::Args(&[DType(int64), DType(int64)]), bool),
    ("LessThanOrEqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("LessThanOrEqualTo_uint64", Args::Args(&[DType(uint64), DType(uint64)]), bool),
    ("LessThan_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("LessThan_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("LessThan_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("LessThan_int64", Args::Args(&[DType(int64), DType(int64)]), bool),
    ("LessThan_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("LessThan_uint64", Args::Args(&[DType(uint64), DType(uint64)]), bool),
    ("Localize", Args::Args(&[DType(Unknown)]), CString),
    ("MakeScopeBool", Args::Args(&[DType(Unknown)]), Scope),
    ("MakeScopeFlag", Args::Args(&[DType(Unknown)]), Scope),
    ("MakeScopeValue", Args::Args(&[DType(Unknown)]), Scope),
    ("Max_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Max_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Max_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Max_int64", Args::Args(&[DType(int64), DType(int64)]), int64),
    ("Max_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("Max_uint64", Args::Args(&[DType(uint64), DType(uint64)]), uint64),
    ("Min_CFixedPoint", Args::Args(&[DType(Unknown), DType(Unknown)]), CFixedPoint),
    ("Min_float", Args::Args(&[DType(Unknown), DType(Unknown)]), float),
    ("Min_int32", Args::Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("Min_int64", Args::Args(&[DType(Unknown), DType(Unknown)]), int64),
    ("Min_uint32", Args::Args(&[DType(Unknown), DType(Unknown)]), uint32),
    ("Min_uint64", Args::Args(&[DType(Unknown), DType(Unknown)]), uint64),
    ("Multiply_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Multiply_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Multiply_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Multiply_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Multiply_int64", Args::Args(&[DType(int64), DType(int64)]), int64),
    ("Multiply_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("Multiply_uint64", Args::Args(&[DType(uint64), DType(uint64)]), uint64),
    ("NOP", Args::Args(&[]), void),
    ("Nbsp", Args::Args(&[]), CString),
    ("Negate_CFixedPoint", Args::Args(&[DType(CFixedPoint)]), CFixedPoint),
    ("Negate_float", Args::Args(&[DType(float)]), float),
    ("Negate_int32", Args::Args(&[DType(int32)]), int32),
    ("Negate_int64", Args::Args(&[DType(int64)]), int64),
    ("Not", Args::Args(&[DType(Unknown)]), bool),
    ("NotEqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("NotEqualTo_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), bool),
    ("NotEqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("NotEqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("NotEqualTo_int64", Args::Args(&[DType(int64), DType(int64)]), bool),
    ("NotEqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("NotEqualTo_uint64", Args::Args(&[DType(uint64), DType(uint64)]), bool),
    ("ObjectsEqual", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("ObserveCountryCommand", Args::Args(&[DType(Unknown)]), Vic3(Command)),
    ("OnCreateAccount", Args::Args(&[]), void),
    ("OnToggleLoginWindow", Args::Args(&[]), void),
    ("OpenAchievements", Args::Args(&[]), void),
    ("OpenGameRules", Args::Args(&[]), void),
    ("Or", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("POPSStatusGetLoginStatus", Args::Args(&[]), CUTF8String),
    ("POPSStatusIsAccountConnected", Args::Args(&[]), bool),
    ("POPSStatusIsLoggedIn", Args::Args(&[]), bool),
    ("POPSStatusIsLoggingIn", Args::Args(&[]), bool),
    ("POPSStatusIsOffline", Args::Args(&[]), bool),
    ("POPSStatusIsSupportConnectedAccount", Args::Args(&[]), bool),
    ("POPStatusGetUserEmailMasked", Args::Args(&[]), CUTF8String),
    ("POPStatusGetUserName", Args::Args(&[]), CUTF8String),
    ("POPStatusIsUserNameEmpty", Args::Args(&[]), bool),
    ("PauseAllConstruction", Args::Args(&[]), Vic3(Command)),
    ("PauseAllConstructionTooltip", Args::Args(&[]), CString),
    ("PdxClearEditBoxText", Args::Args(&[DType(Unknown)]), void),
    ("PdxGetProfilerNames", Args::Args(&[]), Unknown),
    ("PdxGetWidgetScreenSize", Args::Args(&[DType(Unknown)]), CVector2f),
    ("PdxGuiDestroyWidget", Args::Args(&[DType(Unknown)]), void),
    ("PdxGuiEditorMessageBox", Args::Args(&[DType(Unknown)]), void),
    ("PdxGuiInterruptAllAnimations", Args::Args(&[DType(Unknown)]), void),
    ("PdxGuiInterruptThenTriggerAllAnimations", Args::Args(&[DType(Unknown), DType(Unknown)]), void),
    ("PdxGuiTriggerAllAnimations", Args::Args(&[DType(Unknown)]), void),
    ("PdxProfilerFilterNext", Args::Args(&[]), void),
    ("PdxProfilerFilterPrev", Args::Args(&[]), void),
    ("PdxProfilerFilterTimers", Args::Args(&[]), void),
    ("PdxProfilerGetCurrentFrame", Args::Args(&[]), int32),
    ("PdxProfilerGetFrameTimeMs", Args::Args(&[]), float),
    ("PdxProfilerGetNsPerTick", Args::Args(&[]), float),
    ("PdxProfilerGuiGraphLinesEnabled", Args::Args(&[]), bool),
    ("PdxProfilerGuiToggleGraphLines", Args::Args(&[]), void),
    ("PdxProfilerGuiToggleStats", Args::Args(&[]), void),
    ("PdxProfilerGuiTrackCurrentFrame", Args::Args(&[]), void),
    ("PdxProfilerGuiWriteFrameCSV", Args::Args(&[]), void),
    ("PdxProfilerIsRecording", Args::Args(&[]), bool),
    ("PdxProfilerSelectThread", Args::Args(&[]), void),
    ("PdxProfilerSetFrame", Args::Args(&[]), void),
    ("PdxProfilerToggleRecording", Args::Args(&[]), void),
    ("PlayerIsHost", Args::Args(&[]), bool),
    ("ReleaseMode", Args::Args(&[]), bool),
    ("ResumeAllConstruction", Args::Args(&[]), Vic3(Command)),
    ("ResumeAllConstructionTooltip", Args::Args(&[]), CString),
    ("ReturnToMenu", Args::Args(&[]), void),
    ("ScaleToFitElementInside", Args::Args(&[DType(Unknown), DType(Unknown)]), float),
    ("ScaleToFitElementOutside", Args::Args(&[DType(Unknown), DType(Unknown)]), float),
    ("SelectEnumWithString", Args::Args(&[DType(Unknown), DType(Unknown)]), void),
    ("SelectLocalization", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("SelectMapMode", Args::Args(&[]), void),
    ("SelectMapModeByKey", Args::Args(&[DType(Unknown)]), void),
    ("Select_CFixedPoint", Args::Args(&[DType(bool), DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Select_CString", Args::Args(&[DType(bool), DType(CString), DType(CString)]), CString),
    ("Select_CVector2f", Args::Args(&[DType(bool), DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Select_CVector2i", Args::Args(&[DType(bool), DType(CVector2i), DType(CVector2i)]), CVector2i),
    ("Select_CVector3f", Args::Args(&[DType(bool), DType(CVector3f), DType(CVector3f)]), CVector3f),
    ("Select_CVector3i", Args::Args(&[DType(bool), DType(CVector3i), DType(CVector3i)]), CVector3i),
    ("Select_CVector4f", Args::Args(&[DType(bool), DType(CVector4f), DType(CVector4f)]), CVector4f),
    ("Select_CVector4i", Args::Args(&[DType(bool), DType(CVector4i), DType(CVector4i)]), CVector4i),
    ("Select_float", Args::Args(&[DType(bool), DType(float), DType(float)]), float),
    ("Select_int16", Args::Args(&[DType(bool), DType(int16), DType(int16)]), int16),
    ("Select_int32", Args::Args(&[DType(bool), DType(int32), DType(int32)]), int32),
    ("Select_int64", Args::Args(&[DType(bool), DType(int64), DType(int64)]), int64),
    ("Select_int8", Args::Args(&[DType(bool), DType(int8), DType(int8)]), int8),
    ("Select_uint16", Args::Args(&[DType(bool), DType(uint16), DType(uint16)]), uint16),
    ("Select_uint32", Args::Args(&[DType(bool), DType(uint32), DType(uint32)]), uint32),
    ("Select_uint64", Args::Args(&[DType(bool), DType(uint64), DType(uint64)]), uint64),
    ("Select_uint8", Args::Args(&[DType(bool), DType(uint8), DType(uint8)]), uint8),
    ("SetCameraRestrictionsEnabled", Args::Args(&[DType(Unknown)]), void),
    ("SetCanOpenRightClickContextMenu", Args::Args(&[DType(Unknown)]), void),
    ("SetDrawCityDebugGrid", Args::Args(&[DType(Unknown)]), void),
    ("SetDrawCityDebugSpheres", Args::Args(&[DType(Unknown)]), void),
    ("SetDynamicTerrainAutoUpdate", Args::Args(&[DType(Unknown)]), void),
    ("SetDynamicsEnabled", Args::Args(&[DType(Unknown)]), void),
    ("SetInteraction", Args::Args(&[DType(Unknown)]), void),
    ("SetIronmanEnabledStatus", Args::Args(&[DType(Unknown)]), void),
    ("SetRandomPlayableObserverCharacter", Args::Args(&[]), void),
    ("SetTerrainManipulatorProvincesPreview", Args::Args(&[DType(Unknown)]), void),
    ("ShouldAskConfirmation", Args::Args(&[DType(Unknown)]), bool),
    ("ShouldShowAnimationInfo", Args::Args(&[]), bool),
    ("ShouldShowSegmentedControlForSetting", Args::Args(&[DType(Unknown)]), bool),
    ("StringIsEmpty", Args::Args(&[DType(Unknown)]), bool),
    ("Subtract_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Subtract_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Subtract_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Subtract_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Subtract_int64", Args::Args(&[DType(int64), DType(int64)]), int64),
    ("Subtract_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("Subtract_uint64", Args::Args(&[DType(uint64), DType(uint64)]), uint64),
    ("TextureListFormatSize", Args::Args(&[DType(Unknown)]), CString),
    ("TextureListFormatkB", Args::Args(&[DType(Unknown)]), CString),
    ("ToggleEncyclopedia", Args::Args(&[]), void),
    ("ToggleInteraction", Args::Args(&[DType(Unknown)]), void),
    ("ToggleMainMenu", Args::Args(&[]), void),
    ("ToggleMessageSettings", Args::Args(&[]), void),
    ("ToggleMessageSettingsForSingleItem", Args::Args(&[DType(Unknown)]), void),
    ("ToggleMusicPlayer", Args::Args(&[]), void),
    ("ToggleObserveCountry", Args::Args(&[DType(Unknown)]), void),
    ("ToggleThemeSettings", Args::Args(&[]), void),
    ("TransparentIfFalse", Args::Args(&[DType(Unknown)]), float),
    ("TransparentIfTrue", Args::Args(&[DType(Unknown)]), float),
    ("TransparentIfZero", Args::Args(&[DType(Unknown)]), float),
    ("TransparentIfZero_int32", Args::Args(&[DType(Unknown)]), float),
    ("TransparentIfZero_int64", Args::Args(&[DType(Unknown)]), float),
    ("Unfocus", Args::Args(&[DType(Unknown)]), void),
    ("UnforceMapMode", Args::Args(&[]), void),
    ("UpdateDynamicTerrainInAllProvinces", Args::Args(&[]), void),
    ("UsesTimerLocking", Args::Args(&[]), bool),
    ("concept_accepted_culture", Args::Args(&[]), Unknown),
    ("concept_accepted_culture_desc", Args::Args(&[]), Unknown),
    ("concept_accepted_religion", Args::Args(&[]), Unknown),
    ("concept_accepted_religion_desc", Args::Args(&[]), Unknown),
    ("concept_active_interest", Args::Args(&[]), Unknown),
    ("concept_active_interest_desc", Args::Args(&[]), Unknown),
    ("concept_admiral", Args::Args(&[]), Unknown),
    ("concept_admiral_desc", Args::Args(&[]), Unknown),
    ("concept_advance_factor", Args::Args(&[]), Unknown),
    ("concept_advance_factor_desc", Args::Args(&[]), Unknown),
    ("concept_advancement_progress", Args::Args(&[]), Unknown),
    ("concept_advancement_progress_desc", Args::Args(&[]), Unknown),
    ("concept_advancement_speed", Args::Args(&[]), Unknown),
    ("concept_advancement_speed_desc", Args::Args(&[]), Unknown),
    ("concept_agitator", Args::Args(&[]), Unknown),
    ("concept_agitator_desc", Args::Args(&[]), Unknown),
    ("concept_ai_strategy", Args::Args(&[]), Unknown),
    ("concept_ai_strategy_desc", Args::Args(&[]), Unknown),
    ("concept_alliance", Args::Args(&[]), Unknown),
    ("concept_alliance_desc", Args::Args(&[]), Unknown),
    ("concept_approval", Args::Args(&[]), Unknown),
    ("concept_approval_desc", Args::Args(&[]), Unknown),
    ("concept_arable_land", Args::Args(&[]), Unknown),
    ("concept_arable_land_desc", Args::Args(&[]), Unknown),
    ("concept_assimilation", Args::Args(&[]), Unknown),
    ("concept_assimilation_desc", Args::Args(&[]), Unknown),
    ("concept_attitude", Args::Args(&[]), Unknown),
    ("concept_attitude_desc", Args::Args(&[]), Unknown),
    ("concept_attrition", Args::Args(&[]), Unknown),
    ("concept_attrition_desc", Args::Args(&[]), Unknown),
    ("concept_authority", Args::Args(&[]), Unknown),
    ("concept_authority_desc", Args::Args(&[]), Unknown),
    ("concept_available_battalions", Args::Args(&[]), Unknown),
    ("concept_available_battalions_desc", Args::Args(&[]), Unknown),
    ("concept_average_wage", Args::Args(&[]), Unknown),
    ("concept_average_wage_desc", Args::Args(&[]), Unknown),
    ("concept_bankroll", Args::Args(&[]), Unknown),
    ("concept_bankroll_desc", Args::Args(&[]), Unknown),
    ("concept_bankruptcy", Args::Args(&[]), Unknown),
    ("concept_bankruptcy_desc", Args::Args(&[]), Unknown),
    ("concept_base_price", Args::Args(&[]), Unknown),
    ("concept_base_price_desc", Args::Args(&[]), Unknown),
    ("concept_base_success_chance", Args::Args(&[]), Unknown),
    ("concept_base_success_chance_desc", Args::Args(&[]), Unknown),
    ("concept_battalion", Args::Args(&[]), Unknown),
    ("concept_battalion_desc", Args::Args(&[]), Unknown),
    ("concept_battle", Args::Args(&[]), Unknown),
    ("concept_battle_condition", Args::Args(&[]), Unknown),
    ("concept_battle_condition_desc", Args::Args(&[]), Unknown),
    ("concept_battle_desc", Args::Args(&[]), Unknown),
    ("concept_bolster", Args::Args(&[]), Unknown),
    ("concept_bolster_desc", Args::Args(&[]), Unknown),
    ("concept_budget_additional_expenses", Args::Args(&[]), Unknown),
    ("concept_budget_additional_expenses_desc", Args::Args(&[]), Unknown),
    ("concept_budget_additional_income", Args::Args(&[]), Unknown),
    ("concept_budget_additional_income_desc", Args::Args(&[]), Unknown),
    ("concept_budget_construction_goods", Args::Args(&[]), Unknown),
    ("concept_budget_construction_goods_desc", Args::Args(&[]), Unknown),
    ("concept_budget_consumption_taxes", Args::Args(&[]), Unknown),
    ("concept_budget_consumption_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_budget_diplomatic_pacts", Args::Args(&[]), Unknown),
    ("concept_budget_diplomatic_pacts_desc", Args::Args(&[]), Unknown),
    ("concept_budget_dividends_taxes", Args::Args(&[]), Unknown),
    ("concept_budget_dividends_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_budget_goods_for_government_buildings", Args::Args(&[]), Unknown),
    ("concept_budget_goods_for_government_buildings_desc", Args::Args(&[]), Unknown),
    ("concept_budget_goods_for_military_buildings", Args::Args(&[]), Unknown),
    ("concept_budget_goods_for_military_buildings_desc", Args::Args(&[]), Unknown),
    ("concept_budget_government_slaves", Args::Args(&[]), Unknown),
    ("concept_budget_government_slaves_desc", Args::Args(&[]), Unknown),
    ("concept_budget_government_wages", Args::Args(&[]), Unknown),
    ("concept_budget_government_wages_desc", Args::Args(&[]), Unknown),
    ("concept_budget_heathen_taxes", Args::Args(&[]), Unknown),
    ("concept_budget_heathen_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_budget_income_taxes", Args::Args(&[]), Unknown),
    ("concept_budget_income_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_budget_interest", Args::Args(&[]), Unknown),
    ("concept_budget_interest_desc", Args::Args(&[]), Unknown),
    ("concept_budget_investment_income", Args::Args(&[]), Unknown),
    ("concept_budget_investment_income_desc", Args::Args(&[]), Unknown),
    ("concept_budget_land_taxes", Args::Args(&[]), Unknown),
    ("concept_budget_land_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_budget_military_slaves", Args::Args(&[]), Unknown),
    ("concept_budget_military_slaves_desc", Args::Args(&[]), Unknown),
    ("concept_budget_military_wages", Args::Args(&[]), Unknown),
    ("concept_budget_military_wages_desc", Args::Args(&[]), Unknown),
    ("concept_budget_minting", Args::Args(&[]), Unknown),
    ("concept_budget_minting_desc", Args::Args(&[]), Unknown),
    ("concept_budget_per_capita_taxes", Args::Args(&[]), Unknown),
    ("concept_budget_per_capita_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_budget_poll_taxes", Args::Args(&[]), Unknown),
    ("concept_budget_poll_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_budget_wages", Args::Args(&[]), Unknown),
    ("concept_budget_wages_desc", Args::Args(&[]), Unknown),
    ("concept_building", Args::Args(&[]), Unknown),
    ("concept_building_balance", Args::Args(&[]), Unknown),
    ("concept_building_balance_desc", Args::Args(&[]), Unknown),
    ("concept_building_desc", Args::Args(&[]), Unknown),
    ("concept_building_level", Args::Args(&[]), Unknown),
    ("concept_building_level_desc", Args::Args(&[]), Unknown),
    ("concept_building_wage", Args::Args(&[]), Unknown),
    ("concept_building_wage_desc", Args::Args(&[]), Unknown),
    ("concept_bureaucracy", Args::Args(&[]), Unknown),
    ("concept_bureaucracy_desc", Args::Args(&[]), Unknown),
    ("concept_buy_orders", Args::Args(&[]), Unknown),
    ("concept_buy_orders_desc", Args::Args(&[]), Unknown),
    ("concept_canal", Args::Args(&[]), Unknown),
    ("concept_canal_desc", Args::Args(&[]), Unknown),
    ("concept_capacity", Args::Args(&[]), Unknown),
    ("concept_capacity_desc", Args::Args(&[]), Unknown),
    ("concept_capital_state", Args::Args(&[]), Unknown),
    ("concept_capital_state_desc", Args::Args(&[]), Unknown),
    ("concept_capitulation_desire", Args::Args(&[]), Unknown),
    ("concept_capitulation_desire_desc", Args::Args(&[]), Unknown),
    ("concept_cash_reserves", Args::Args(&[]), Unknown),
    ("concept_cash_reserves_desc", Args::Args(&[]), Unknown),
    ("concept_casualties", Args::Args(&[]), Unknown),
    ("concept_casualties_desc", Args::Args(&[]), Unknown),
    ("concept_character", Args::Args(&[]), Unknown),
    ("concept_character_desc", Args::Args(&[]), Unknown),
    ("concept_character_role", Args::Args(&[]), Unknown),
    ("concept_character_role_desc", Args::Args(&[]), Unknown),
    ("concept_character_trait", Args::Args(&[]), Unknown),
    ("concept_character_trait_desc", Args::Args(&[]), Unknown),
    ("concept_civil_war", Args::Args(&[]), Unknown),
    ("concept_civil_war_desc", Args::Args(&[]), Unknown),
    ("concept_claim", Args::Args(&[]), Unknown),
    ("concept_claim_desc", Args::Args(&[]), Unknown),
    ("concept_clout", Args::Args(&[]), Unknown),
    ("concept_clout_desc", Args::Args(&[]), Unknown),
    ("concept_colonial_growth", Args::Args(&[]), Unknown),
    ("concept_colonial_growth_desc", Args::Args(&[]), Unknown),
    ("concept_colonization_rights", Args::Args(&[]), Unknown),
    ("concept_colonization_rights_desc", Args::Args(&[]), Unknown),
    ("concept_colony", Args::Args(&[]), Unknown),
    ("concept_colony_desc", Args::Args(&[]), Unknown),
    ("concept_combat_width", Args::Args(&[]), Unknown),
    ("concept_combat_width_desc", Args::Args(&[]), Unknown),
    ("concept_command_limit", Args::Args(&[]), Unknown),
    ("concept_command_limit_desc", Args::Args(&[]), Unknown),
    ("concept_commander", Args::Args(&[]), Unknown),
    ("concept_commander_desc", Args::Args(&[]), Unknown),
    ("concept_commander_rank", Args::Args(&[]), Unknown),
    ("concept_commander_rank_desc", Args::Args(&[]), Unknown),
    ("concept_concept", Args::Args(&[]), Unknown),
    ("concept_concept_desc", Args::Args(&[]), Unknown),
    ("concept_confidence", Args::Args(&[]), Unknown),
    ("concept_confidence_desc", Args::Args(&[]), Unknown),
    ("concept_conscript_battalion", Args::Args(&[]), Unknown),
    ("concept_conscript_battalion_desc", Args::Args(&[]), Unknown),
    ("concept_conscription_center", Args::Args(&[]), Unknown),
    ("concept_conscription_center_desc", Args::Args(&[]), Unknown),
    ("concept_construction", Args::Args(&[]), Unknown),
    ("concept_construction_desc", Args::Args(&[]), Unknown),
    ("concept_construction_queue", Args::Args(&[]), Unknown),
    ("concept_construction_queue_desc", Args::Args(&[]), Unknown),
    ("concept_consumption_tax", Args::Args(&[]), Unknown),
    ("concept_consumption_tax_desc", Args::Args(&[]), Unknown),
    ("concept_conversion", Args::Args(&[]), Unknown),
    ("concept_conversion_desc", Args::Args(&[]), Unknown),
    ("concept_convoy_cost", Args::Args(&[]), Unknown),
    ("concept_convoy_cost_desc", Args::Args(&[]), Unknown),
    ("concept_convoys", Args::Args(&[]), Unknown),
    ("concept_convoys_desc", Args::Args(&[]), Unknown),
    ("concept_countdown_to_war", Args::Args(&[]), Unknown),
    ("concept_countdown_to_war_desc", Args::Args(&[]), Unknown),
    ("concept_country", Args::Args(&[]), Unknown),
    ("concept_country_desc", Args::Args(&[]), Unknown),
    ("concept_country_tier", Args::Args(&[]), Unknown),
    ("concept_country_tier_desc", Args::Args(&[]), Unknown),
    ("concept_credit", Args::Args(&[]), Unknown),
    ("concept_credit_desc", Args::Args(&[]), Unknown),
    ("concept_cultural_heritage_trait", Args::Args(&[]), Unknown),
    ("concept_cultural_heritage_trait_desc", Args::Args(&[]), Unknown),
    ("concept_cultural_trait", Args::Args(&[]), Unknown),
    ("concept_cultural_trait_desc", Args::Args(&[]), Unknown),
    ("concept_cultural_turmoil", Args::Args(&[]), Unknown),
    ("concept_cultural_turmoil_desc", Args::Args(&[]), Unknown),
    ("concept_culture", Args::Args(&[]), Unknown),
    ("concept_culture_desc", Args::Args(&[]), Unknown),
    ("concept_customs_union", Args::Args(&[]), Unknown),
    ("concept_customs_union_desc", Args::Args(&[]), Unknown),
    ("concept_dead", Args::Args(&[]), Unknown),
    ("concept_dead_desc", Args::Args(&[]), Unknown),
    ("concept_decay", Args::Args(&[]), Unknown),
    ("concept_decay_desc", Args::Args(&[]), Unknown),
    ("concept_decentralized_nation", Args::Args(&[]), Unknown),
    ("concept_decentralized_nation_desc", Args::Args(&[]), Unknown),
    ("concept_declared_interest", Args::Args(&[]), Unknown),
    ("concept_declared_interest_desc", Args::Args(&[]), Unknown),
    ("concept_decree", Args::Args(&[]), Unknown),
    ("concept_decree_desc", Args::Args(&[]), Unknown),
    ("concept_default", Args::Args(&[]), Unknown),
    ("concept_default_desc", Args::Args(&[]), Unknown),
    ("concept_defense", Args::Args(&[]), Unknown),
    ("concept_defense_desc", Args::Args(&[]), Unknown),
    ("concept_defensive_pact", Args::Args(&[]), Unknown),
    ("concept_defensive_pact_desc", Args::Args(&[]), Unknown),
    ("concept_dependent_income", Args::Args(&[]), Unknown),
    ("concept_dependent_income_desc", Args::Args(&[]), Unknown),
    ("concept_dependents", Args::Args(&[]), Unknown),
    ("concept_dependents_desc", Args::Args(&[]), Unknown),
    ("concept_devastation", Args::Args(&[]), Unknown),
    ("concept_devastation_desc", Args::Args(&[]), Unknown),
    ("concept_diplomatic_action", Args::Args(&[]), Unknown),
    ("concept_diplomatic_action_desc", Args::Args(&[]), Unknown),
    ("concept_diplomatic_incident", Args::Args(&[]), Unknown),
    ("concept_diplomatic_incident_desc", Args::Args(&[]), Unknown),
    ("concept_diplomatic_lens", Args::Args(&[]), Unknown),
    ("concept_diplomatic_lens_desc", Args::Args(&[]), Unknown),
    ("concept_diplomatic_maneuvers", Args::Args(&[]), Unknown),
    ("concept_diplomatic_maneuvers_desc", Args::Args(&[]), Unknown),
    ("concept_diplomatic_pact", Args::Args(&[]), Unknown),
    ("concept_diplomatic_pact_desc", Args::Args(&[]), Unknown),
    ("concept_diplomatic_play", Args::Args(&[]), Unknown),
    ("concept_diplomatic_play_desc", Args::Args(&[]), Unknown),
    ("concept_discrimination", Args::Args(&[]), Unknown),
    ("concept_discrimination_desc", Args::Args(&[]), Unknown),
    ("concept_disenfranchised", Args::Args(&[]), Unknown),
    ("concept_disenfranchised_desc", Args::Args(&[]), Unknown),
    ("concept_dividends", Args::Args(&[]), Unknown),
    ("concept_dividends_desc", Args::Args(&[]), Unknown),
    ("concept_dominion", Args::Args(&[]), Unknown),
    ("concept_dominion_desc", Args::Args(&[]), Unknown),
    ("concept_economy_health", Args::Args(&[]), Unknown),
    ("concept_economy_health_desc", Args::Args(&[]), Unknown),
    ("concept_economy_of_scale", Args::Args(&[]), Unknown),
    ("concept_economy_of_scale_desc", Args::Args(&[]), Unknown),
    ("concept_education_access", Args::Args(&[]), Unknown),
    ("concept_education_access_desc", Args::Args(&[]), Unknown),
    ("concept_election", Args::Args(&[]), Unknown),
    ("concept_election_desc", Args::Args(&[]), Unknown),
    ("concept_embargo", Args::Args(&[]), Unknown),
    ("concept_embargo_desc", Args::Args(&[]), Unknown),
    ("concept_enactment_advance", Args::Args(&[]), Unknown),
    ("concept_enactment_advance_desc", Args::Args(&[]), Unknown),
    ("concept_enactment_debate", Args::Args(&[]), Unknown),
    ("concept_enactment_debate_desc", Args::Args(&[]), Unknown),
    ("concept_enactment_of_laws", Args::Args(&[]), Unknown),
    ("concept_enactment_of_laws_desc", Args::Args(&[]), Unknown),
    ("concept_enactment_phase", Args::Args(&[]), Unknown),
    ("concept_enactment_phase_desc", Args::Args(&[]), Unknown),
    ("concept_enactment_setback", Args::Args(&[]), Unknown),
    ("concept_enactment_setback_desc", Args::Args(&[]), Unknown),
    ("concept_enactment_stall", Args::Args(&[]), Unknown),
    ("concept_enactment_stall_desc", Args::Args(&[]), Unknown),
    ("concept_enactment_success", Args::Args(&[]), Unknown),
    ("concept_enactment_success_desc", Args::Args(&[]), Unknown),
    ("concept_end_of_discussion_factor", Args::Args(&[]), Unknown),
    ("concept_end_of_discussion_factor_desc", Args::Args(&[]), Unknown),
    ("concept_endorse_oppose", Args::Args(&[]), Unknown),
    ("concept_endorse_oppose_desc", Args::Args(&[]), Unknown),
    ("concept_escalation", Args::Args(&[]), Unknown),
    ("concept_escalation_desc", Args::Args(&[]), Unknown),
    ("concept_escort_convoys", Args::Args(&[]), Unknown),
    ("concept_escort_convoys_desc", Args::Args(&[]), Unknown),
    ("concept_exile", Args::Args(&[]), Unknown),
    ("concept_exile_desc", Args::Args(&[]), Unknown),
    ("concept_expected_sol", Args::Args(&[]), Unknown),
    ("concept_expected_sol_desc", Args::Args(&[]), Unknown),
    ("concept_field_promotion", Args::Args(&[]), Unknown),
    ("concept_field_promotion_desc", Args::Args(&[]), Unknown),
    ("concept_flotilla", Args::Args(&[]), Unknown),
    ("concept_flotilla_desc", Args::Args(&[]), Unknown),
    ("concept_front", Args::Args(&[]), Unknown),
    ("concept_front_desc", Args::Args(&[]), Unknown),
    ("concept_fully_mobilized_battalions", Args::Args(&[]), Unknown),
    ("concept_fully_mobilized_battalions_desc", Args::Args(&[]), Unknown),
    ("concept_garrison", Args::Args(&[]), Unknown),
    ("concept_garrison_desc", Args::Args(&[]), Unknown),
    ("concept_gdp", Args::Args(&[]), Unknown),
    ("concept_gdp_desc", Args::Args(&[]), Unknown),
    ("concept_general", Args::Args(&[]), Unknown),
    ("concept_general_desc", Args::Args(&[]), Unknown),
    ("concept_gold_reserves", Args::Args(&[]), Unknown),
    ("concept_gold_reserves_desc", Args::Args(&[]), Unknown),
    ("concept_good", Args::Args(&[]), Unknown),
    ("concept_good_consumption", Args::Args(&[]), Unknown),
    ("concept_good_consumption_desc", Args::Args(&[]), Unknown),
    ("concept_good_desc", Args::Args(&[]), Unknown),
    ("concept_good_production", Args::Args(&[]), Unknown),
    ("concept_good_production_desc", Args::Args(&[]), Unknown),
    ("concept_goods_substitution", Args::Args(&[]), Unknown),
    ("concept_goods_substitution_desc", Args::Args(&[]), Unknown),
    ("concept_government", Args::Args(&[]), Unknown),
    ("concept_government_building", Args::Args(&[]), Unknown),
    ("concept_government_building_desc", Args::Args(&[]), Unknown),
    ("concept_government_construction", Args::Args(&[]), Unknown),
    ("concept_government_construction_desc", Args::Args(&[]), Unknown),
    ("concept_government_desc", Args::Args(&[]), Unknown),
    ("concept_government_dividends", Args::Args(&[]), Unknown),
    ("concept_government_dividends_desc", Args::Args(&[]), Unknown),
    ("concept_government_expenses", Args::Args(&[]), Unknown),
    ("concept_government_expenses_desc", Args::Args(&[]), Unknown),
    ("concept_government_good", Args::Args(&[]), Unknown),
    ("concept_government_good_desc", Args::Args(&[]), Unknown),
    ("concept_government_ownership_share", Args::Args(&[]), Unknown),
    ("concept_government_ownership_share_desc", Args::Args(&[]), Unknown),
    ("concept_government_reform", Args::Args(&[]), Unknown),
    ("concept_government_reform_desc", Args::Args(&[]), Unknown),
    ("concept_government_type", Args::Args(&[]), Unknown),
    ("concept_government_type_desc", Args::Args(&[]), Unknown),
    ("concept_government_wage", Args::Args(&[]), Unknown),
    ("concept_government_wage_desc", Args::Args(&[]), Unknown),
    ("concept_great_power", Args::Args(&[]), Unknown),
    ("concept_great_power_desc", Args::Args(&[]), Unknown),
    ("concept_head_of_state", Args::Args(&[]), Unknown),
    ("concept_head_of_state_desc", Args::Args(&[]), Unknown),
    ("concept_heir", Args::Args(&[]), Unknown),
    ("concept_heir_desc", Args::Args(&[]), Unknown),
    ("concept_homeland", Args::Args(&[]), Unknown),
    ("concept_homeland_desc", Args::Args(&[]), Unknown),
    ("concept_hq", Args::Args(&[]), Unknown),
    ("concept_hq_desc", Args::Args(&[]), Unknown),
    ("concept_humiliation", Args::Args(&[]), Unknown),
    ("concept_humiliation_desc", Args::Args(&[]), Unknown),
    ("concept_ideology", Args::Args(&[]), Unknown),
    ("concept_ideology_desc", Args::Args(&[]), Unknown),
    ("concept_in_government", Args::Args(&[]), Unknown),
    ("concept_in_government_desc", Args::Args(&[]), Unknown),
    ("concept_in_opposition", Args::Args(&[]), Unknown),
    ("concept_in_opposition_desc", Args::Args(&[]), Unknown),
    ("concept_in_reserve", Args::Args(&[]), Unknown),
    ("concept_in_reserve_desc", Args::Args(&[]), Unknown),
    ("concept_inactive_interest", Args::Args(&[]), Unknown),
    ("concept_inactive_interest_desc", Args::Args(&[]), Unknown),
    ("concept_incorporated_state", Args::Args(&[]), Unknown),
    ("concept_incorporated_state_desc", Args::Args(&[]), Unknown),
    ("concept_individual", Args::Args(&[]), Unknown),
    ("concept_individual_desc", Args::Args(&[]), Unknown),
    ("concept_infamy", Args::Args(&[]), Unknown),
    ("concept_infamy_desc", Args::Args(&[]), Unknown),
    ("concept_influence", Args::Args(&[]), Unknown),
    ("concept_influence_desc", Args::Args(&[]), Unknown),
    ("concept_influential", Args::Args(&[]), Unknown),
    ("concept_influential_desc", Args::Args(&[]), Unknown),
    ("concept_infrastructure", Args::Args(&[]), Unknown),
    ("concept_infrastructure_desc", Args::Args(&[]), Unknown),
    ("concept_infrastructure_usage", Args::Args(&[]), Unknown),
    ("concept_infrastructure_usage_desc", Args::Args(&[]), Unknown),
    ("concept_initiator", Args::Args(&[]), Unknown),
    ("concept_initiator_desc", Args::Args(&[]), Unknown),
    ("concept_innovation", Args::Args(&[]), Unknown),
    ("concept_innovation_desc", Args::Args(&[]), Unknown),
    ("concept_input_goods_shortage", Args::Args(&[]), Unknown),
    ("concept_input_goods_shortage_desc", Args::Args(&[]), Unknown),
    ("concept_input_mult", Args::Args(&[]), Unknown),
    ("concept_input_mult_desc", Args::Args(&[]), Unknown),
    ("concept_insignificant_power", Args::Args(&[]), Unknown),
    ("concept_insignificant_power_desc", Args::Args(&[]), Unknown),
    ("concept_instant_diplomatic_action", Args::Args(&[]), Unknown),
    ("concept_instant_diplomatic_action_desc", Args::Args(&[]), Unknown),
    ("concept_institution", Args::Args(&[]), Unknown),
    ("concept_institution_desc", Args::Args(&[]), Unknown),
    ("concept_interest", Args::Args(&[]), Unknown),
    ("concept_interest_desc", Args::Args(&[]), Unknown),
    ("concept_interest_group", Args::Args(&[]), Unknown),
    ("concept_interest_group_attraction", Args::Args(&[]), Unknown),
    ("concept_interest_group_attraction_desc", Args::Args(&[]), Unknown),
    ("concept_interest_group_desc", Args::Args(&[]), Unknown),
    ("concept_interest_group_trait", Args::Args(&[]), Unknown),
    ("concept_interest_group_trait_desc", Args::Args(&[]), Unknown),
    ("concept_investment_level", Args::Args(&[]), Unknown),
    ("concept_investment_level_desc", Args::Args(&[]), Unknown),
    ("concept_investment_pool", Args::Args(&[]), Unknown),
    ("concept_investment_pool_desc", Args::Args(&[]), Unknown),
    ("concept_isolated_state", Args::Args(&[]), Unknown),
    ("concept_isolated_state_desc", Args::Args(&[]), Unknown),
    ("concept_journal_entry", Args::Args(&[]), Unknown),
    ("concept_journal_entry_desc", Args::Args(&[]), Unknown),
    ("concept_junior_partner", Args::Args(&[]), Unknown),
    ("concept_junior_partner_desc", Args::Args(&[]), Unknown),
    ("concept_kill_rate", Args::Args(&[]), Unknown),
    ("concept_kill_rate_desc", Args::Args(&[]), Unknown),
    ("concept_land_trade_capacity", Args::Args(&[]), Unknown),
    ("concept_land_trade_capacity_desc", Args::Args(&[]), Unknown),
    ("concept_law", Args::Args(&[]), Unknown),
    ("concept_law_desc", Args::Args(&[]), Unknown),
    ("concept_law_group", Args::Args(&[]), Unknown),
    ("concept_law_group_desc", Args::Args(&[]), Unknown),
    ("concept_leader", Args::Args(&[]), Unknown),
    ("concept_leader_desc", Args::Args(&[]), Unknown),
    ("concept_legitimacy", Args::Args(&[]), Unknown),
    ("concept_legitimacy_desc", Args::Args(&[]), Unknown),
    ("concept_life_experience", Args::Args(&[]), Unknown),
    ("concept_life_experience_desc", Args::Args(&[]), Unknown),
    ("concept_literacy", Args::Args(&[]), Unknown),
    ("concept_literacy_desc", Args::Args(&[]), Unknown),
    ("concept_loans", Args::Args(&[]), Unknown),
    ("concept_loans_desc", Args::Args(&[]), Unknown),
    ("concept_local_price", Args::Args(&[]), Unknown),
    ("concept_local_price_desc", Args::Args(&[]), Unknown),
    ("concept_lower_strata", Args::Args(&[]), Unknown),
    ("concept_lower_strata_desc", Args::Args(&[]), Unknown),
    ("concept_loyalist", Args::Args(&[]), Unknown),
    ("concept_loyalist_desc", Args::Args(&[]), Unknown),
    ("concept_major_power", Args::Args(&[]), Unknown),
    ("concept_major_power_desc", Args::Args(&[]), Unknown),
    ("concept_maneuver", Args::Args(&[]), Unknown),
    ("concept_maneuver_desc", Args::Args(&[]), Unknown),
    ("concept_manpower", Args::Args(&[]), Unknown),
    ("concept_manpower_desc", Args::Args(&[]), Unknown),
    ("concept_marginalized", Args::Args(&[]), Unknown),
    ("concept_marginalized_desc", Args::Args(&[]), Unknown),
    ("concept_market", Args::Args(&[]), Unknown),
    ("concept_market_access", Args::Args(&[]), Unknown),
    ("concept_market_access_desc", Args::Args(&[]), Unknown),
    ("concept_market_capital", Args::Args(&[]), Unknown),
    ("concept_market_capital_desc", Args::Args(&[]), Unknown),
    ("concept_market_desc", Args::Args(&[]), Unknown),
    ("concept_market_good_policy", Args::Args(&[]), Unknown),
    ("concept_market_good_policy_desc", Args::Args(&[]), Unknown),
    ("concept_market_impact", Args::Args(&[]), Unknown),
    ("concept_market_impact_desc", Args::Args(&[]), Unknown),
    ("concept_market_owner", Args::Args(&[]), Unknown),
    ("concept_market_owner_desc", Args::Args(&[]), Unknown),
    ("concept_market_price", Args::Args(&[]), Unknown),
    ("concept_market_price_desc", Args::Args(&[]), Unknown),
    ("concept_market_share", Args::Args(&[]), Unknown),
    ("concept_market_share_desc", Args::Args(&[]), Unknown),
    ("concept_message_settings_feed", Args::Args(&[]), Unknown),
    ("concept_message_settings_feed_desc", Args::Args(&[]), Unknown),
    ("concept_message_settings_none", Args::Args(&[]), Unknown),
    ("concept_message_settings_none_desc", Args::Args(&[]), Unknown),
    ("concept_message_settings_popup", Args::Args(&[]), Unknown),
    ("concept_message_settings_popup_desc", Args::Args(&[]), Unknown),
    ("concept_message_settings_toast", Args::Args(&[]), Unknown),
    ("concept_message_settings_toast_desc", Args::Args(&[]), Unknown),
    ("concept_middle_strata", Args::Args(&[]), Unknown),
    ("concept_middle_strata_desc", Args::Args(&[]), Unknown),
    ("concept_migration", Args::Args(&[]), Unknown),
    ("concept_migration_desc", Args::Args(&[]), Unknown),
    ("concept_migration_pull", Args::Args(&[]), Unknown),
    ("concept_migration_pull_desc", Args::Args(&[]), Unknown),
    ("concept_migration_target", Args::Args(&[]), Unknown),
    ("concept_migration_target_desc", Args::Args(&[]), Unknown),
    ("concept_military_building", Args::Args(&[]), Unknown),
    ("concept_military_building_desc", Args::Args(&[]), Unknown),
    ("concept_military_good", Args::Args(&[]), Unknown),
    ("concept_military_good_desc", Args::Args(&[]), Unknown),
    ("concept_military_lens", Args::Args(&[]), Unknown),
    ("concept_military_lens_desc", Args::Args(&[]), Unknown),
    ("concept_military_wage", Args::Args(&[]), Unknown),
    ("concept_military_wage_desc", Args::Args(&[]), Unknown),
    ("concept_minor_power", Args::Args(&[]), Unknown),
    ("concept_minor_power_desc", Args::Args(&[]), Unknown),
    ("concept_mobilize_battalion", Args::Args(&[]), Unknown),
    ("concept_mobilize_battalion_desc", Args::Args(&[]), Unknown),
    ("concept_mobilize_general", Args::Args(&[]), Unknown),
    ("concept_mobilize_general_desc", Args::Args(&[]), Unknown),
    ("concept_modifier", Args::Args(&[]), Unknown),
    ("concept_modifier_desc", Args::Args(&[]), Unknown),
    ("concept_momentum", Args::Args(&[]), Unknown),
    ("concept_momentum_desc", Args::Args(&[]), Unknown),
    ("concept_money", Args::Args(&[]), Unknown),
    ("concept_money_desc", Args::Args(&[]), Unknown),
    ("concept_monument", Args::Args(&[]), Unknown),
    ("concept_monument_desc", Args::Args(&[]), Unknown),
    ("concept_morale", Args::Args(&[]), Unknown),
    ("concept_morale_demoralized", Args::Args(&[]), Unknown),
    ("concept_morale_demoralized_desc", Args::Args(&[]), Unknown),
    ("concept_morale_desc", Args::Args(&[]), Unknown),
    ("concept_nation_formation", Args::Args(&[]), Unknown),
    ("concept_nation_formation_desc", Args::Args(&[]), Unknown),
    ("concept_native_uprising", Args::Args(&[]), Unknown),
    ("concept_native_uprising_desc", Args::Args(&[]), Unknown),
    ("concept_naval_invasion_support", Args::Args(&[]), Unknown),
    ("concept_naval_invasion_support_desc", Args::Args(&[]), Unknown),
    ("concept_neighbors", Args::Args(&[]), Unknown),
    ("concept_neighbors_desc", Args::Args(&[]), Unknown),
    ("concept_neutral", Args::Args(&[]), Unknown),
    ("concept_neutral_desc", Args::Args(&[]), Unknown),
    ("concept_neutrality", Args::Args(&[]), Unknown),
    ("concept_neutrality_desc", Args::Args(&[]), Unknown),
    ("concept_normal_wage", Args::Args(&[]), Unknown),
    ("concept_normal_wage_desc", Args::Args(&[]), Unknown),
    ("concept_obligation", Args::Args(&[]), Unknown),
    ("concept_obligation_desc", Args::Args(&[]), Unknown),
    ("concept_observer_mode", Args::Args(&[]), Unknown),
    ("concept_observer_mode_desc", Args::Args(&[]), Unknown),
    ("concept_obsession", Args::Args(&[]), Unknown),
    ("concept_obsession_desc", Args::Args(&[]), Unknown),
    ("concept_occupancy", Args::Args(&[]), Unknown),
    ("concept_occupancy_desc", Args::Args(&[]), Unknown),
    ("concept_occupation", Args::Args(&[]), Unknown),
    ("concept_occupation_desc", Args::Args(&[]), Unknown),
    ("concept_offense", Args::Args(&[]), Unknown),
    ("concept_offense_desc", Args::Args(&[]), Unknown),
    ("concept_ongoing_diplomatic_action", Args::Args(&[]), Unknown),
    ("concept_ongoing_diplomatic_action_desc", Args::Args(&[]), Unknown),
    ("concept_open_market", Args::Args(&[]), Unknown),
    ("concept_open_market_desc", Args::Args(&[]), Unknown),
    ("concept_opening_moves", Args::Args(&[]), Unknown),
    ("concept_opening_moves_desc", Args::Args(&[]), Unknown),
    ("concept_order", Args::Args(&[]), Unknown),
    ("concept_order_desc", Args::Args(&[]), Unknown),
    ("concept_overlord", Args::Args(&[]), Unknown),
    ("concept_overlord_desc", Args::Args(&[]), Unknown),
    ("concept_ownership_share", Args::Args(&[]), Unknown),
    ("concept_ownership_share_desc", Args::Args(&[]), Unknown),
    ("concept_party", Args::Args(&[]), Unknown),
    ("concept_party_desc", Args::Args(&[]), Unknown),
    ("concept_party_leader", Args::Args(&[]), Unknown),
    ("concept_party_leader_desc", Args::Args(&[]), Unknown),
    ("concept_party_whip", Args::Args(&[]), Unknown),
    ("concept_party_whip_desc", Args::Args(&[]), Unknown),
    ("concept_peace_deal", Args::Args(&[]), Unknown),
    ("concept_peace_deal_desc", Args::Args(&[]), Unknown),
    ("concept_personal_union", Args::Args(&[]), Unknown),
    ("concept_personal_union_desc", Args::Args(&[]), Unknown),
    ("concept_political_lens", Args::Args(&[]), Unknown),
    ("concept_political_lens_desc", Args::Args(&[]), Unknown),
    ("concept_political_movement", Args::Args(&[]), Unknown),
    ("concept_political_movement_desc", Args::Args(&[]), Unknown),
    ("concept_political_movement_placated", Args::Args(&[]), Unknown),
    ("concept_political_movement_placated_desc", Args::Args(&[]), Unknown),
    ("concept_political_movement_radicalism", Args::Args(&[]), Unknown),
    ("concept_political_movement_radicalism_desc", Args::Args(&[]), Unknown),
    ("concept_political_movement_support", Args::Args(&[]), Unknown),
    ("concept_political_movement_support_desc", Args::Args(&[]), Unknown),
    ("concept_political_strength", Args::Args(&[]), Unknown),
    ("concept_political_strength_desc", Args::Args(&[]), Unknown),
    ("concept_politically_unaligned_aligned", Args::Args(&[]), Unknown),
    ("concept_politically_unaligned_aligned_desc", Args::Args(&[]), Unknown),
    ("concept_politician", Args::Args(&[]), Unknown),
    ("concept_politician_desc", Args::Args(&[]), Unknown),
    ("concept_pop", Args::Args(&[]), Unknown),
    ("concept_pop_desc", Args::Args(&[]), Unknown),
    ("concept_pop_growth", Args::Args(&[]), Unknown),
    ("concept_pop_growth_desc", Args::Args(&[]), Unknown),
    ("concept_pop_income", Args::Args(&[]), Unknown),
    ("concept_pop_income_desc", Args::Args(&[]), Unknown),
    ("concept_pop_needs", Args::Args(&[]), Unknown),
    ("concept_pop_needs_desc", Args::Args(&[]), Unknown),
    ("concept_pop_qualifications", Args::Args(&[]), Unknown),
    ("concept_pop_qualifications_desc", Args::Args(&[]), Unknown),
    ("concept_popularity", Args::Args(&[]), Unknown),
    ("concept_popularity_desc", Args::Args(&[]), Unknown),
    ("concept_port_connection", Args::Args(&[]), Unknown),
    ("concept_port_connection_desc", Args::Args(&[]), Unknown),
    ("concept_potential_battalions", Args::Args(&[]), Unknown),
    ("concept_potential_battalions_desc", Args::Args(&[]), Unknown),
    ("concept_power_projection", Args::Args(&[]), Unknown),
    ("concept_power_projection_desc", Args::Args(&[]), Unknown),
    ("concept_powerful", Args::Args(&[]), Unknown),
    ("concept_powerful_desc", Args::Args(&[]), Unknown),
    ("concept_prestige", Args::Args(&[]), Unknown),
    ("concept_prestige_desc", Args::Args(&[]), Unknown),
    ("concept_primary_cultures", Args::Args(&[]), Unknown),
    ("concept_primary_cultures_desc", Args::Args(&[]), Unknown),
    ("concept_primary_demand", Args::Args(&[]), Unknown),
    ("concept_primary_demand_desc", Args::Args(&[]), Unknown),
    ("concept_principal", Args::Args(&[]), Unknown),
    ("concept_principal_desc", Args::Args(&[]), Unknown),
    ("concept_private_construction", Args::Args(&[]), Unknown),
    ("concept_private_construction_desc", Args::Args(&[]), Unknown),
    ("concept_production_lens", Args::Args(&[]), Unknown),
    ("concept_production_lens_desc", Args::Args(&[]), Unknown),
    ("concept_production_method", Args::Args(&[]), Unknown),
    ("concept_production_method_desc", Args::Args(&[]), Unknown),
    ("concept_productivity", Args::Args(&[]), Unknown),
    ("concept_productivity_desc", Args::Args(&[]), Unknown),
    ("concept_profession", Args::Args(&[]), Unknown),
    ("concept_profession_desc", Args::Args(&[]), Unknown),
    ("concept_protectorate", Args::Args(&[]), Unknown),
    ("concept_protectorate_desc", Args::Args(&[]), Unknown),
    ("concept_province", Args::Args(&[]), Unknown),
    ("concept_province_desc", Args::Args(&[]), Unknown),
    ("concept_puppet", Args::Args(&[]), Unknown),
    ("concept_puppet_desc", Args::Args(&[]), Unknown),
    ("concept_radical", Args::Args(&[]), Unknown),
    ("concept_radical_desc", Args::Args(&[]), Unknown),
    ("concept_raid_convoys", Args::Args(&[]), Unknown),
    ("concept_raid_convoys_desc", Args::Args(&[]), Unknown),
    ("concept_rank", Args::Args(&[]), Unknown),
    ("concept_rank_desc", Args::Args(&[]), Unknown),
    ("concept_recognized_power", Args::Args(&[]), Unknown),
    ("concept_recognized_power_desc", Args::Args(&[]), Unknown),
    ("concept_recovery_rate", Args::Args(&[]), Unknown),
    ("concept_recovery_rate_desc", Args::Args(&[]), Unknown),
    ("concept_reinvestment", Args::Args(&[]), Unknown),
    ("concept_reinvestment_desc", Args::Args(&[]), Unknown),
    ("concept_relations", Args::Args(&[]), Unknown),
    ("concept_relations_desc", Args::Args(&[]), Unknown),
    ("concept_religion", Args::Args(&[]), Unknown),
    ("concept_religion_desc", Args::Args(&[]), Unknown),
    ("concept_religious_trait", Args::Args(&[]), Unknown),
    ("concept_religious_trait_desc", Args::Args(&[]), Unknown),
    ("concept_resource_potential", Args::Args(&[]), Unknown),
    ("concept_resource_potential_desc", Args::Args(&[]), Unknown),
    ("concept_revenue", Args::Args(&[]), Unknown),
    ("concept_revenue_desc", Args::Args(&[]), Unknown),
    ("concept_revolution", Args::Args(&[]), Unknown),
    ("concept_revolution_desc", Args::Args(&[]), Unknown),
    ("concept_revolution_progression_speed", Args::Args(&[]), Unknown),
    ("concept_revolution_progression_speed_desc", Args::Args(&[]), Unknown),
    ("concept_rivalry", Args::Args(&[]), Unknown),
    ("concept_rivalry_desc", Args::Args(&[]), Unknown),
    ("concept_ruler", Args::Args(&[]), Unknown),
    ("concept_ruler_desc", Args::Args(&[]), Unknown),
    ("concept_sea_node", Args::Args(&[]), Unknown),
    ("concept_sea_node_desc", Args::Args(&[]), Unknown),
    ("concept_secession", Args::Args(&[]), Unknown),
    ("concept_secession_desc", Args::Args(&[]), Unknown),
    ("concept_secondary_demand", Args::Args(&[]), Unknown),
    ("concept_secondary_demand_desc", Args::Args(&[]), Unknown),
    ("concept_sell_orders", Args::Args(&[]), Unknown),
    ("concept_sell_orders_desc", Args::Args(&[]), Unknown),
    ("concept_senior_partner", Args::Args(&[]), Unknown),
    ("concept_senior_partner_desc", Args::Args(&[]), Unknown),
    ("concept_shipping_lane", Args::Args(&[]), Unknown),
    ("concept_shipping_lane_desc", Args::Args(&[]), Unknown),
    ("concept_shipping_lane_effectiveness", Args::Args(&[]), Unknown),
    ("concept_shipping_lane_effectiveness_desc", Args::Args(&[]), Unknown),
    ("concept_slavery", Args::Args(&[]), Unknown),
    ("concept_slavery_desc", Args::Args(&[]), Unknown),
    ("concept_sol", Args::Args(&[]), Unknown),
    ("concept_sol_desc", Args::Args(&[]), Unknown),
    ("concept_sovereignty", Args::Args(&[]), Unknown),
    ("concept_sovereignty_desc", Args::Args(&[]), Unknown),
    ("concept_split_state", Args::Args(&[]), Unknown),
    ("concept_split_state_desc", Args::Args(&[]), Unknown),
    ("concept_state", Args::Args(&[]), Unknown),
    ("concept_state_desc", Args::Args(&[]), Unknown),
    ("concept_state_region", Args::Args(&[]), Unknown),
    ("concept_state_region_desc", Args::Args(&[]), Unknown),
    ("concept_state_religion", Args::Args(&[]), Unknown),
    ("concept_state_religion_desc", Args::Args(&[]), Unknown),
    ("concept_strategic_desire", Args::Args(&[]), Unknown),
    ("concept_strategic_desire_desc", Args::Args(&[]), Unknown),
    ("concept_strategic_objective", Args::Args(&[]), Unknown),
    ("concept_strategic_objective_desc", Args::Args(&[]), Unknown),
    ("concept_strategic_region", Args::Args(&[]), Unknown),
    ("concept_strategic_region_desc", Args::Args(&[]), Unknown),
    ("concept_subject", Args::Args(&[]), Unknown),
    ("concept_subject_desc", Args::Args(&[]), Unknown),
    ("concept_subsidies", Args::Args(&[]), Unknown),
    ("concept_subsidies_desc", Args::Args(&[]), Unknown),
    ("concept_subsidized_wage", Args::Args(&[]), Unknown),
    ("concept_subsidized_wage_desc", Args::Args(&[]), Unknown),
    ("concept_subsistence_building", Args::Args(&[]), Unknown),
    ("concept_subsistence_building_desc", Args::Args(&[]), Unknown),
    ("concept_subsistence_output", Args::Args(&[]), Unknown),
    ("concept_subsistence_output_desc", Args::Args(&[]), Unknown),
    ("concept_supply", Args::Args(&[]), Unknown),
    ("concept_supply_desc", Args::Args(&[]), Unknown),
    ("concept_supply_network", Args::Args(&[]), Unknown),
    ("concept_supply_network_desc", Args::Args(&[]), Unknown),
    ("concept_supply_route", Args::Args(&[]), Unknown),
    ("concept_supply_route_desc", Args::Args(&[]), Unknown),
    ("concept_suppress", Args::Args(&[]), Unknown),
    ("concept_suppress_desc", Args::Args(&[]), Unknown),
    ("concept_sway", Args::Args(&[]), Unknown),
    ("concept_sway_desc", Args::Args(&[]), Unknown),
    ("concept_sympathy", Args::Args(&[]), Unknown),
    ("concept_sympathy_desc", Args::Args(&[]), Unknown),
    ("concept_taboo", Args::Args(&[]), Unknown),
    ("concept_taboo_desc", Args::Args(&[]), Unknown),
    ("concept_target", Args::Args(&[]), Unknown),
    ("concept_target_desc", Args::Args(&[]), Unknown),
    ("concept_tariffs", Args::Args(&[]), Unknown),
    ("concept_tariffs_desc", Args::Args(&[]), Unknown),
    ("concept_tax_capacity", Args::Args(&[]), Unknown),
    ("concept_tax_capacity_desc", Args::Args(&[]), Unknown),
    ("concept_tax_waste", Args::Args(&[]), Unknown),
    ("concept_tax_waste_desc", Args::Args(&[]), Unknown),
    ("concept_taxes", Args::Args(&[]), Unknown),
    ("concept_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_technology", Args::Args(&[]), Unknown),
    ("concept_technology_desc", Args::Args(&[]), Unknown),
    ("concept_technology_era", Args::Args(&[]), Unknown),
    ("concept_technology_era_desc", Args::Args(&[]), Unknown),
    ("concept_technology_spread", Args::Args(&[]), Unknown),
    ("concept_technology_spread_desc", Args::Args(&[]), Unknown),
    ("concept_tension", Args::Args(&[]), Unknown),
    ("concept_tension_desc", Args::Args(&[]), Unknown),
    ("concept_terrain", Args::Args(&[]), Unknown),
    ("concept_terrain_desc", Args::Args(&[]), Unknown),
    ("concept_theater", Args::Args(&[]), Unknown),
    ("concept_theater_desc", Args::Args(&[]), Unknown),
    ("concept_throughput", Args::Args(&[]), Unknown),
    ("concept_throughput_desc", Args::Args(&[]), Unknown),
    ("concept_timed_modifier", Args::Args(&[]), Unknown),
    ("concept_timed_modifier_desc", Args::Args(&[]), Unknown),
    ("concept_trade_agreement", Args::Args(&[]), Unknown),
    ("concept_trade_agreement_desc", Args::Args(&[]), Unknown),
    ("concept_trade_lens", Args::Args(&[]), Unknown),
    ("concept_trade_lens_desc", Args::Args(&[]), Unknown),
    ("concept_trade_revenue", Args::Args(&[]), Unknown),
    ("concept_trade_revenue_desc", Args::Args(&[]), Unknown),
    ("concept_trade_route", Args::Args(&[]), Unknown),
    ("concept_trade_route_competitiveness", Args::Args(&[]), Unknown),
    ("concept_trade_route_competitiveness_desc", Args::Args(&[]), Unknown),
    ("concept_trade_route_desc", Args::Args(&[]), Unknown),
    ("concept_training_rate", Args::Args(&[]), Unknown),
    ("concept_training_rate_desc", Args::Args(&[]), Unknown),
    ("concept_transfer_of_power", Args::Args(&[]), Unknown),
    ("concept_transfer_of_power_desc", Args::Args(&[]), Unknown),
    ("concept_treasury", Args::Args(&[]), Unknown),
    ("concept_treasury_desc", Args::Args(&[]), Unknown),
    ("concept_treaty_port", Args::Args(&[]), Unknown),
    ("concept_treaty_port_desc", Args::Args(&[]), Unknown),
    ("concept_tributary", Args::Args(&[]), Unknown),
    ("concept_tributary_desc", Args::Args(&[]), Unknown),
    ("concept_turmoil", Args::Args(&[]), Unknown),
    ("concept_turmoil_desc", Args::Args(&[]), Unknown),
    ("concept_under_construction", Args::Args(&[]), Unknown),
    ("concept_under_construction_desc", Args::Args(&[]), Unknown),
    ("concept_unemployed", Args::Args(&[]), Unknown),
    ("concept_unemployed_desc", Args::Args(&[]), Unknown),
    ("concept_unification", Args::Args(&[]), Unknown),
    ("concept_unification_candidate", Args::Args(&[]), Unknown),
    ("concept_unification_candidate_desc", Args::Args(&[]), Unknown),
    ("concept_unification_desc", Args::Args(&[]), Unknown),
    ("concept_unification_supporter", Args::Args(&[]), Unknown),
    ("concept_unification_supporter_desc", Args::Args(&[]), Unknown),
    ("concept_unincorporated_state", Args::Args(&[]), Unknown),
    ("concept_unincorporated_state_desc", Args::Args(&[]), Unknown),
    ("concept_unit", Args::Args(&[]), Unknown),
    ("concept_unit_desc", Args::Args(&[]), Unknown),
    ("concept_unrealized_taxes", Args::Args(&[]), Unknown),
    ("concept_unrealized_taxes_desc", Args::Args(&[]), Unknown),
    ("concept_unrecognized_power", Args::Args(&[]), Unknown),
    ("concept_unrecognized_power_desc", Args::Args(&[]), Unknown),
    ("concept_upper_strata", Args::Args(&[]), Unknown),
    ("concept_upper_strata_desc", Args::Args(&[]), Unknown),
    ("concept_urbanization", Args::Args(&[]), Unknown),
    ("concept_urbanization_desc", Args::Args(&[]), Unknown),
    ("concept_vassal", Args::Args(&[]), Unknown),
    ("concept_vassal_desc", Args::Args(&[]), Unknown),
    ("concept_votes", Args::Args(&[]), Unknown),
    ("concept_votes_desc", Args::Args(&[]), Unknown),
    ("concept_war", Args::Args(&[]), Unknown),
    ("concept_war_desc", Args::Args(&[]), Unknown),
    ("concept_war_exhaustion", Args::Args(&[]), Unknown),
    ("concept_war_exhaustion_desc", Args::Args(&[]), Unknown),
    ("concept_war_goal", Args::Args(&[]), Unknown),
    ("concept_war_goal_desc", Args::Args(&[]), Unknown),
    ("concept_war_leader", Args::Args(&[]), Unknown),
    ("concept_war_leader_desc", Args::Args(&[]), Unknown),
    ("concept_war_reparations", Args::Args(&[]), Unknown),
    ("concept_war_reparations_desc", Args::Args(&[]), Unknown),
    ("concept_war_support", Args::Args(&[]), Unknown),
    ("concept_war_support_desc", Args::Args(&[]), Unknown),
    ("concept_wealth", Args::Args(&[]), Unknown),
    ("concept_wealth_desc", Args::Args(&[]), Unknown),
    ("concept_welfare_payments", Args::Args(&[]), Unknown),
    ("concept_welfare_payments_desc", Args::Args(&[]), Unknown),
    ("concept_workforce", Args::Args(&[]), Unknown),
    ("concept_workforce_desc", Args::Args(&[]), Unknown),
    ("concept_working_adults", Args::Args(&[]), Unknown),
    ("concept_working_adults_desc", Args::Args(&[]), Unknown),
    ("concept_wounded", Args::Args(&[]), Unknown),
    ("concept_wounded_desc", Args::Args(&[]), Unknown),
]
