// LAST UPDATED IMPERATOR VERSION 2.0.4
pub const DLC_IMPERATOR: &[&str] = &[
    "Heirs of Alexander",
    "Epirus Flavor Pack",
    "Magna Graecia",
    "The Punic Wars",
    "Hellenistic World Flavor Pack",
];

/// A list of music provided by DLCs, for people who don't have them
pub const DLC_MUSIC: &[&str] = &[
    // TODO
];

// LAST UPDATED IMPERATOR VERSION 2.0.4
pub const COMMON_DIRS: &[&str] = &[
    "common/achievements",
    "common/advice",
    "common/ai_budget",
    "common/ai_budget_categories",
    "common/ai_diplochance",
    "common/ai_objectives",
    "common/ai_plan_goals",
    "common/ambitions",
    "common/buildings",
    "common/character_interactions",
    "common/coat_of_arms/coat_of_arms",
    "common/coat_of_arms/options",
    "common/coat_of_arms/template_lists",
    "common/combat_tactics",
    "common/cultures",
    "common/customizable_localization",
    "common/deathreasons",
    "common/defines",
    "common/deities",
    "common/deity_categories",
    "common/diplomatic_stances",
    "common/economic_policies",
    "common/effect_localization",
    "common/ethnicities",
    "common/event_pictures",
    "common/event_themes",
    "common/faction_impact",
    "common/game_concepts",
    "common/genes",
    "common/governments",
    "common/governor_policies",
    "common/graphical_culture_types",
    "common/great_work_categories",
    "common/great_work_effect_tiers",
    "common/great_work_effects",
    "common/great_work_materials",
    "common/great_work_modules",
    "common/great_work_names",
    "common/great_work_templates",
    "common/heritage",
    "common/ideas",
    "common/inventions",
    "common/laws",
    "common/legion_distinctions",
    "common/levy_templates",
    "common/loyalty",
    "common/military_traditions",
    "common/missions",
    "common/modifier_icons",
    "common/modifiers",
    "common/named_colors",
    "common/objective_hunt_pirates.txt",
    "common/offices",
    "common/on_action",
    "common/opinions",
    "common/party_agendas",
    "common/party_changes",
    "common/party_types",
    "common/pop_types",
    "common/prices",
    "common/province_names",
    "common/province_ranks",
    "common/religions",
    "common/script_values",
    "common/scripted_effects",
    "common/scripted_guis",
    "common/scripted_lists",
    "common/scripted_modifiers",
    "common/scripted_tests",
    "common/scripted_triggers",
    "common/subject_types",
    "common/technology_tables",
    "common/terrain_types",
    "common/titles",
    "common/trade_goods",
    "common/tradition_groups",
    "common/traits",
    "common/unit_abilities",
    "common/units",
    "common/wargoals",
];

// LAST UPDATED IMPERATOR VERSION 2.0.4
pub const COMMON_SUBDIRS_OK: &[&str] = &["common/defines", "common/on_action"];
