&[
    ("AIWatchWindowsEnabled", Args(&[]), bool),
    ("Abs_CFixedPoint", Args(&[DType(CFixedPoint)]), CFixedPoint),
    ("Abs_float", Args(&[DType(float)]), float),
    ("Abs_int32", Args(&[DType(int32)]), int32),
    ("AccessLocalPlayerCachedData", Args(&[]), Ck3(LocalPlayerCachedData)),
    ("AccessMapEditorLayerBorders", Args(&[]), Unknown),
    ("AccessSuggestionItems", Args(&[]), Unknown),
    ("AccessTopBar", Args(&[]), Unknown),
    ("AddLine", Args(&[DType(CString)]), CString),
    ("AddLocalizationIf", Args(&[DType(bool), DType(CString)]), CString),
    ("AddParagraph", Args(&[DType(Unknown)]), CString),
    ("AddTextIf", Args(&[DType(bool), DType(CString)]), CString),
    ("AddWatchWindow", Args(&[DType(Scope)]), void),
    ("Add_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Add_CVector2f", Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Add_float", Args(&[DType(float), DType(float)]), float),
    ("Add_int32", Args(&[DType(int32), DType(int32)]), int32),
    ("Add_uint32", Args(&[DType(uint32), DType(uint32)]), uint32),
    ("And", Args(&[DType(bool), DType(bool)]), bool),
    ("AreAchievementsAvailable", Args(&[]), bool),
    ("BindFoldOutContext", Args(&[]), void),
    ("BoolTo1And2", Args(&[DType(bool)]), int32),
    ("BoolTo2And1", Args(&[DType(bool)]), int32),
    ("CalcProgressBetweenDates", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), float),
    ("CalcResolutionLimitAspectRatio", Args(&[]), CVector2f),
    ("CalculateBreakdownItems", Args(&[DType(Unknown)]), Unknown),
    ("CanAnyoneUnpause", Args(&[]), bool),
    ("CanChangeMapMode", Args(&[]), bool),
    ("CanDecreaseGameSpeed", Args(&[]), bool),
    ("CanEditSettingsAfterHost", Args(&[]), bool),
    ("CanGetAchievements", Args(&[]), bool),
    ("CanIncreaseGameSpeed", Args(&[]), bool),
    ("CanOpenLobby", Args(&[]), bool),
    ("ClearErrorLog", Args(&[]), void),
    ("ClearExploringRealms", Args(&[]), void),
    ("ClearHighlightedStruggleBorder", Args(&[]), void),
    ("ClearHostError", Args(&[]), void),
    ("ClearObserver", Args(&[]), void),
    ("ClearResetReactiveTutorialPopup", Args(&[]), void),
    ("CloseAllTooltips", Args(&[]), void),
    ("CloseGameView", Args(&[DType(Unknown)]), void),
    ("ConcatIfNeitherEmpty", Args(&[DType(CString), DType(CString)]), CString),
    ("Concatenate", Args(&[DType(CString), DType(CString)]), CString),
    ("Concept", Args(&[IType(Item::GameConcept), DType(CString)]), CString),
    ("CopyBuildVersionInfoToClipboard", Args(&[]), void),
    ("CopyServerID", Args(&[]), void),
    ("CurrentAndMaxToProgressbarValueInt32", Args(&[DType(int32), DType(int32)]), float),
    ("DataModelFirst", Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelHasItems", Args(&[DType(Unknown)]), bool),
    ("DataModelLast", Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelSkipFirst", Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelSkipLast", Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("DataModelSubSpan", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("DaysPerMonth", Args(&[]), int32),
    ("DaysPerWeek", Args(&[]), int32),
    ("DaysPerYear", Args(&[]), int32),
    ("DefaultOnCharacterClick", Args(&[DType(uint32)]), void),
    ("DefaultOnCharacterRightClick", Args(&[DType(uint32)]), void),
    ("DefaultOnCoatOfArmsClick", Args(&[DType(uint32)]), void),
    ("DefaultOnCoatOfArmsRightClick", Args(&[DType(uint32)]), void),
    ("DefaultOnDynastyCoatOfArmsClick", Args(&[DType(uint32)]), void),
    ("DefaultOnHouseCoatOfArmsClick", Args(&[DType(uint32)]), void),
    ("DefaultOnRaidClick", Args(&[DType(Ck3(Raid))]), void),
    ("DefaultOnRealmFlagClick", Args(&[DType(uint32)]), void),
    ("DefaultOnRealmFlagRightClick", Args(&[DType(uint32)]), void),
    ("DefaultOnSiegeClick", Args(&[DType(uint32)]), void),
    ("Divide_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Divide_CVector2f", Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Divide_float", Args(&[DType(float), DType(float)]), float),
    ("Divide_int32", Args(&[DType(int32), DType(int32)]), int32),
    ("Divide_uint32", Args(&[DType(uint32), DType(uint32)]), uint32),
    ("DoubleToFloat", Args(&[DType(double)]), float),
    ("EqualTo_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("EqualTo_CVector2f", Args(&[DType(CVector2f), DType(CVector2f)]), bool),
    ("EqualTo_float", Args(&[DType(float), DType(float)]), bool),
    ("EqualTo_int32", Args(&[DType(int32), DType(int32)]), bool),
    ("EqualTo_string", Args(&[DType(CString), DType(CString)]), bool),
    ("EqualTo_uint32", Args(&[DType(uint32), DType(uint32)]), bool),
    ("ErrorTooltip", Args(&[]), CString),
    ("ExecuteConsoleCommand", Args(&[DType(CString)]), void),
    ("ExecuteConsoleCommands", Args(&[DType(CString)]), void),
    ("ExecuteConsoleCommandsForced", Args(&[DType(CString)]), void),
    ("FixedPointToFloat", Args(&[DType(CFixedPoint)]), float),
    ("FixedPointToInt", Args(&[DType(CFixedPoint)]), int32),
    ("FixedPointToProgressbarValue", Args(&[DType(CFixedPoint)]), float),
    ("GameHasMultiplePlayers", Args(&[]), bool),
    ("GameIsMultiplayer", Args(&[]), bool),
    ("GameOverDesc", Args(&[]), CString),
    ("GetAbsoluteMousePosition", Args(&[]), CVector2f),
    ("GetAbsoluteMousePositionInteger", Args(&[]), CVector2i),
    ("GetAccoladeType", Args(&[IType(Item::AccoladeType)]), Ck3(AccoladeType)),
    ("GetAchievementsAvailableString", Args(&[]), CString),
    ("GetActivityGuestInviteRule", Args(&[IType(Item::GuestInviteRule)]), Ck3(ActivityGuestInviteRule)),
    ("GetActivityIntent", Args(&[IType(Item::ActivityIntent)]), Ck3(ActivityIntent)),
    ("GetActivityLocale", Args(&[IType(Item::ActivityLocale)]), void),
    ("GetActivityPulseAction", Args(&[IType(Item::PulseAction)]), Unknown),
    ("GetActivityType", Args(&[IType(Item::ActivityType)]), Ck3(ActivityType)),
    ("GetAllAccoladeTypes", Args(&[]), Unknown),
    ("GetAllActivityGuestInviteRules", Args(&[]), Unknown),
    ("GetAllActivityIntents", Args(&[]), Unknown),
    ("GetAllActivityLocales", Args(&[]), Unknown),
    ("GetAllActivityPulseActions", Args(&[]), Unknown),
    ("GetAllActivityTypes", Args(&[]), Unknown),
    ("GetAllArtifactTypes", Args(&[]), Unknown),
    ("GetAllArtifactVisualTypes", Args(&[]), Unknown),
    ("GetAllBookmarkGroups", Args(&[]), Unknown),
    ("GetAllBookmarkPortraits", Args(&[]), Unknown),
    ("GetAllBookmarks", Args(&[]), Unknown),
    ("GetAllBuildings", Args(&[]), Unknown),
    ("GetAllCasusBelliTypes", Args(&[]), Unknown),
    ("GetAllCatalystTypes", Args(&[]), Unknown),
    ("GetAllCharacterInteractionCategorys", Args(&[]), Unknown),
    ("GetAllCharacterInteractions", Args(&[]), Unknown),
    ("GetAllCharacterMemoryTypes", Args(&[]), Unknown),
    ("GetAllCombatEffects", Args(&[]), Unknown),
    ("GetAllCouncilPositionTypes", Args(&[]), Unknown),
    ("GetAllCouncilTaskTypes", Args(&[]), Unknown),
    ("GetAllCourtAmenitiesSettings", Args(&[]), Unknown),
    ("GetAllCourtPositionCategories", Args(&[]), Unknown),
    ("GetAllCourtPositionCategorys", Args(&[]), Unknown),
    ("GetAllCourtPositionTypes", Args(&[]), Unknown),
    ("GetAllCourtTypes", Args(&[]), Unknown),
    ("GetAllCultureEraTypes", Args(&[]), Unknown),
    ("GetAllCultureInnovationTypes", Args(&[]), Unknown),
    ("GetAllCulturePillars", Args(&[]), Unknown),
    ("GetAllCultureTemplates", Args(&[]), Unknown),
    ("GetAllCultureTraditions", Args(&[]), Unknown),
    ("GetAllDecisions", Args(&[]), Unknown),
    ("GetAllDlcs", Args(&[]), Unknown),
    ("GetAllDynastyHouseTemplates", Args(&[]), Unknown),
    ("GetAllDynastyLegacys", Args(&[]), Unknown),
    ("GetAllDynastyPerks", Args(&[]), Unknown),
    ("GetAllDynastyTemplates", Args(&[]), Unknown),
    ("GetAllFaithDoctrineGroups", Args(&[]), Unknown),
    ("GetAllFaithDoctrines", Args(&[]), Unknown),
    ("GetAllFocusTypes", Args(&[]), Unknown),
    ("GetAllGeographicalRegions", Args(&[]), Unknown),
    ("GetAllGovernmentTypes", Args(&[]), Unknown),
    ("GetAllHoldingTypes", Args(&[]), Unknown),
    ("GetAllHolySites", Args(&[]), Unknown),
    ("GetAllIllustrations", Args(&[]), Unknown),
    ("GetAllImportantActionTypes", Args(&[]), Unknown),
    ("GetAllInspirationTypes", Args(&[]), Unknown),
    ("GetAllInventorySlotTypes", Args(&[]), Unknown),
    ("GetAllLandedTitpleTemplates", Args(&[]), Unknown),
    ("GetAllLawGroups", Args(&[]), Unknown),
    ("GetAllLaws", Args(&[]), Unknown),
    ("GetAllLifestyles", Args(&[]), Unknown),
    ("GetAllLightTypes", Args(&[]), Unknown),
    ("GetAllMandates", Args(&[]), Unknown),
    ("GetAllMenAtArmsTypes", Args(&[]), Unknown),
    ("GetAllMessageTypes", Args(&[]), Unknown),
    ("GetAllNicknames", Args(&[]), Unknown),
    ("GetAllPerks", Args(&[]), Unknown),
    ("GetAllReligionFamilys", Args(&[]), Unknown),
    ("GetAllSchemeTypes", Args(&[]), Unknown),
    ("GetAllScriptedRelations", Args(&[]), Unknown),
    ("GetAllSecretTypes", Args(&[]), Unknown),
    ("GetAllStaticModifiers", Args(&[]), Unknown),
    ("GetAllStrugglePhases", Args(&[]), Unknown),
    ("GetAllStruggleTypes", Args(&[]), Unknown),
    ("GetAllSuggestionTypes", Args(&[]), Unknown),
    ("GetAllTerrains", Args(&[]), Unknown),
    ("GetAllTraits", Args(&[]), Unknown),
    ("GetAllTravelOptions", Args(&[]), Unknown),
    ("GetAllTravelPointOfInterestTypes", Args(&[]), Unknown),
    ("GetAllVassalContractTypes", Args(&[]), Unknown),
    ("GetAllVassalStances", Args(&[]), Unknown),
    ("GetAnimatedBookmarkPortrait", Args(&[DType(Unknown), DType(Unknown), DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetAnimationTooltip", Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetArtifactType", Args(&[IType(Item::ArtifactType)]), Unknown),
    ("GetArtifactVisualType", Args(&[IType(Item::ArtifactVisual)]), Unknown),
    ("GetAutosaveName", Args(&[]), CUTF8String),
    ("GetBookmark", Args(&[IType(Item::Bookmark)]), Unknown),
    ("GetBookmarkGroup", Args(&[IType(Item::BookmarkGroup)]), Unknown),
    ("GetBookmarkPortrait", Args(&[DType(Unknown)]), Unknown),
    ("GetBuildVersionDescription", Args(&[]), CString),
    ("GetBuildVersionDescriptionWithClickToCopy", Args(&[]), CString),
    ("GetBuilding", Args(&[IType(Item::Building)]), Unknown),
    ("GetCanGoToFrontend", Args(&[]), bool),
    ("GetCanGoToFrontendDesc", Args(&[]), CString),
    ("GetCasusBelliType", Args(&[IType(Item::CasusBelli)]), Unknown),
    ("GetCatalystType", Args(&[IType(Item::Catalyst)]), Unknown),
    ("GetCharacterInteraction", Args(&[IType(Item::CharacterInteraction)]), Unknown),
    ("GetCharacterInteractionCategory", Args(&[IType(Item::CharacterInteractionCategory)]), Unknown),
    ("GetCharacterMemoryType", Args(&[DType(Unknown)]), void),
    ("GetCoatOfArmsDesignerEmblemTextureCategories", Args(&[]), Unknown),
    ("GetCombatEffect", Args(&[DType(Unknown)]), void),
    ("GetCouncilPositionType", Args(&[DType(Unknown)]), Unknown),
    ("GetCouncilTaskType", Args(&[DType(Unknown)]), Unknown),
    ("GetCourtAmenitiesSetting", Args(&[DType(Unknown)]), Unknown),
    ("GetCourtGrandeurDiffFromExpectedLevelModifier", Args(&[DType(Unknown)]), Unknown),
    ("GetCourtGrandeurLevelModifier", Args(&[DType(Unknown)]), Unknown),
    ("GetCourtPositionCategory", Args(&[DType(Unknown)]), Unknown),
    ("GetCourtPositionType", Args(&[DType(Unknown)]), Unknown),
    ("GetCourtScenePositionForSlot", Args(&[DType(Unknown), DType(Unknown)]), CVector2f),
    ("GetCourtType", Args(&[DType(Unknown)]), Unknown),
    ("GetCreditPortraitsForGroup", Args(&[DType(Unknown)]), Unknown),
    ("GetCultureEraType", Args(&[DType(Unknown)]), Unknown),
    ("GetCultureInnovationType", Args(&[DType(Unknown)]), Unknown),
    ("GetCulturePillar", Args(&[DType(Unknown)]), Unknown),
    ("GetCultureTemplate", Args(&[IType(Item::Culture)]), Ck3(CultureTemplate)),
    ("GetCultureTradition", Args(&[DType(Unknown)]), Unknown),
    ("GetCurrentDate", Args(&[]), Date),
    ("GetCurrentDateStringWithSyncInfo", Args(&[]), CString),
    ("GetCurrentDateWithDiff", Args(&[DType(int32)]), CString),
    ("GetCurrentDateWithDiffLong", Args(&[DType(int32)]), CString),
    ("GetCurrentDateWithDiffShort", Args(&[DType(int32)]), CString),
    ("GetCurrentFps", Args(&[]), float),
    ("GetCurrentGameSpeed", Args(&[]), int32),
    ("GetCurrentGameSpeedText", Args(&[]), CString),
    ("GetCurrentLoadingScreen", Args(&[]), Unknown),
    ("GetDataModelSize", Args(&[DType(Unknown)]), int32),
    ("GetDecision", Args(&[DType(Unknown)]), Unknown),
    ("GetDecisionWithKey", Args(&[IType(Item::Decision)]), Unknown),
    ("GetDecreaseSpeedTooltip", Args(&[]), CString),
    ("GetDefaultServerName", Args(&[]), CUTF8String),
    ("GetDefine", Args(&[DType(CString), DType(CString)]), Unknown),
    ("GetDefineAtIndex", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetDisbandAllTooltip", Args(&[]), CString),
    ("GetDlc", Args(&[DType(Unknown)]), Unknown),
    ("GetDynastyHouseTemplate", Args(&[DType(Unknown)]), void),
    ("GetDynastyLegacy", Args(&[DType(Unknown)]), void),
    ("GetDynastyPerk", Args(&[DType(Unknown)]), Unknown),
    ("GetDynastyPrestigeLevelEffect", Args(&[DType(Unknown)]), CString),
    ("GetDynastyPrestigeLevelName", Args(&[DType(Unknown)]), CString),
    ("GetDynastyPrestigeLevelNext", Args(&[DType(Unknown)]), CString),
    ("GetDynastyTemplate", Args(&[DType(Unknown)]), void),
    ("GetEconomyMapModeTooltip", Args(&[DType(Unknown)]), CString),
    ("GetEducationTraits", Args(&[]), Unknown),
    ("GetEnumIndex", Args(&[DType(Unknown)]), CVector2i),
    ("GetErrorHoofFrame", Args(&[]), int32),
    ("GetEthnicities", Args(&[]), Unknown),
    ("GetFaithDoctrine", Args(&[IType(Item::Doctrine)]), Unknown),
    ("GetFaithDoctrineGroup", Args(&[DType(Unknown)]), Unknown),
    ("GetFertility", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CFixedPoint),
    ("GetFertilityLevel", Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetFocusType", Args(&[DType(Unknown)]), Unknown),
    ("GetGameTimeDifferenceForDiffDays", Args(&[DType(int32)]), CString),
    ("GetGameTimeDifferenceForDiffMonths", Args(&[DType(int32), DType(bool)]), CString),
    ("GetGameTimeDurationDays", Args(&[DType(Unknown)]), CString),
    ("GetGameTimeDurationMonths", Args(&[DType(Unknown)]), CString),
    ("GetGameVersionDisplay", Args(&[]), CString),
    ("GetGameVersionInfo", Args(&[]), CString),
    ("GetGameVersionInfoShort", Args(&[]), CString),
    ("GetGeographicalRegion", Args(&[IType(Item::Region)]), void),
    ("GetGlobalList", Args(&[DType(Unknown)]), Unknown),
    ("GetGlobalVariable", Args(&[DType(Unknown)]), Unknown),
    ("GetGovernment", Args(&[DType(Unknown)]), Unknown),
    ("GetGovernmentType", Args(&[DType(Unknown)]), Unknown),
    ("GetGuiPositionFromPercentCoordinates", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetHighlightTint", Args(&[]), CVector4f),
    ("GetHoldingType", Args(&[DType(Unknown)]), Unknown),
    ("GetHolySite", Args(&[IType(Item::HolySite)]), Unknown),
    ("GetHostError", Args(&[]), CUTF8String),
    ("GetHostilityDescription", Args(&[DType(Unknown)]), CString),
    ("GetHostilityLevelName", Args(&[DType(Unknown)]), CString),
    ("GetIllustration", Args(&[IType(Item::ScriptedIllustration)]), void),
    ("GetImportantActionType", Args(&[DType(Unknown)]), Unknown),
    ("GetIncreaseSpeedTooltip", Args(&[]), CString),
    ("GetInspirationType", Args(&[DType(Unknown)]), Unknown),
    ("GetInvParentScale", Args(&[DType(Unknown)]), float),
    ("GetInventorySlotType", Args(&[DType(Unknown)]), Unknown),
    ("GetInventorySlotTypes", Args(&[]), Unknown),
    ("GetIsChecked", Args(&[DType(Unknown)]), bool),
    ("GetKnightCount", Args(&[DType(Unknown)]), int32),
    ("GetKnightLimit", Args(&[DType(Unknown)]), int32),
    ("GetKnightLimitBreakdown", Args(&[DType(Unknown)]), CString),
    ("GetLaggingPlayerName", Args(&[]), CString),
    ("GetLandedTitpleTemplate", Args(&[DType(Unknown)]), void),
    ("GetLaw", Args(&[DType(Unknown)]), Unknown),
    ("GetLawGroup", Args(&[DType(Unknown)]), Unknown),
    ("GetLeadingTroopsBonus", Args(&[]), CString),
    ("GetLifestyle", Args(&[IType(Item::Lifestyle)]), Unknown),
    ("GetLifestyleTooltipForCharacter", Args(&[DType(Unknown)]), CString),
    ("GetLifestyleTooltipWarnings", Args(&[DType(Unknown)]), CString),
    ("GetLoadTip", Args(&[]), CString),
    ("GetLoadedMods", Args(&[]), CString),
    ("GetLocalPlayerPietyTextIcon", Args(&[]), CString),
    ("GetLocalizedDefine", Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetLocalizedDefineAtIndex", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("GetMPChecksum", Args(&[]), CString),
    ("GetMandate", Args(&[DType(Unknown)]), void),
    ("GetMaxStress", Args(&[]), int32),
    ("GetMenAtArmsType", Args(&[DType(Unknown)]), Unknown),
    ("GetMessageType", Args(&[DType(Unknown)]), Unknown),
    ("GetModifier", Args(&[IType(Item::Modifier)]), Unknown),
    ("GetNickname", Args(&[IType(Item::Nickname)]), void),
    ("GetNullCharacter", Args(&[]), Ck3(Character)),
    ("GetNullCharacterDataModel", Args(&[DType(Unknown)]), Unknown),
    ("GetNullProperty", Args(&[]), Unknown),
    ("GetNullProvince", Args(&[]), Unknown),
    ("GetNumberAbove_int32", Args(&[DType(int32), DType(int32)]), int32),
    ("GetOpenLobbyTooltip", Args(&[]), CString),
    ("GetOtherRulerDesignerTraits", Args(&[]), Unknown),
    ("GetPausedBy", Args(&[]), CString),
    ("GetPausedByEventReason", Args(&[]), CString),
    ("GetPerk", Args(&[IType(Item::Perk)]), Unknown),
    ("GetPersonalityTraits", Args(&[]), Unknown),
    ("GetPietyLevelDesc", Args(&[DType(Unknown)]), CString),
    ("GetPietyLevelIcon", Args(&[DType(Unknown)]), Unknown),
    ("GetPietyLevelName", Args(&[DType(Unknown)]), CString),
    ("GetPlayer", Args(&[]), Ck3(Character)),
    ("GetPlayerArmyComposition", Args(&[]), Unknown),
    ("GetPlayerBalance", Args(&[]), CFixedPoint),
    ("GetPlayerRaiseAllMenAtArmsTooltip", Args(&[]), CString),
    ("GetPlayerRaiseAllRaidersTooltip", Args(&[]), CString),
    ("GetPlayerRaiseAllTooltip", Args(&[]), CString),
    ("GetPlayersCount", Args(&[]), int32),
    ("GetPortraitTextureFromDna", Args(&[DType(Unknown), DType(Unknown)]), Unknown),
    ("GetPrestigeLevelDesc", Args(&[DType(Unknown)]), CString),
    ("GetPrestigeLevelIcon", Args(&[DType(Unknown)]), Unknown),
    ("GetPrestigeLevelName", Args(&[DType(Unknown)]), CString),
    ("GetProgressBarValueMax", Args(&[DType(float), DType(float)]), int32),
    ("GetProgressBarValueMaxOther", Args(&[DType(float), DType(float)]), int32),
    ("GetProgressBarValueMaxOtherScaled", Args(&[DType(float), DType(float), DType(int32)]), int32),
    ("GetProgressBarValueMaxScaled", Args(&[DType(float), DType(float), DType(int32)]), int32),
    ("GetProgressBarValuePair", Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("GetRandomFrontendIllustration", Args(&[]), Unknown),
    ("GetRandomLogInfo", Args(&[]), CString),
    ("GetRelation", Args(&[IType(Item::Relation)]), Unknown),
    ("GetReligionFamily", Args(&[DType(Unknown)]), void),
    ("GetResolutionWithAspectRatio", Args(&[]), CVector2f),
    ("GetRoyalCourtHoveredArtifact", Args(&[]), Unknown),
    ("GetRoyalCourtHoveredCharacter", Args(&[]), Unknown),
    ("GetRoyalCourtSelectedArtifact", Args(&[]), Unknown),
    ("GetRoyalCourtSelectedCharacter", Args(&[]), Unknown),
    ("GetSceneSettingsName", Args(&[DType(Unknown)]), CString),
    ("GetSchemeType", Args(&[IType(Item::Scheme)]), Unknown),
    ("GetScriptedRelation", Args(&[IType(Item::Relation)]), Unknown),
    ("GetSecretType", Args(&[IType(Item::Secret)]), Unknown),
    ("GetSegmentedProgressChanceBar", Args(&[DType(Unknown), DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetSegmentedProgressTargetBar", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetSmartBrushInterpolationNames", Args(&[]), Unknown),
    ("GetSmartBrushPatternNames", Args(&[]), Unknown),
    ("GetStaticModifier", Args(&[IType(Item::Modifier)]), Unknown),
    ("GetStringSettingText", Args(&[DType(Unknown)]), CString),
    ("GetString_CPdxFloatRect", Args(&[DType(Ck3(CPdxFloatRect))]), CString),
    ("GetString_CPdxIntRect", Args(&[DType(Ck3(CPdxIntRect))]), CString),
    ("GetString_CVector2f", Args(&[DType(CVector2f)]), CString),
    ("GetString_CVector2i", Args(&[DType(CVector2i)]), CString),
    ("GetString_CVector3f", Args(&[DType(CVector3f)]), CString),
    ("GetString_CVector3i", Args(&[DType(CVector3i)]), CString),
    ("GetString_CVector4f", Args(&[DType(CVector4f)]), CString),
    ("GetString_CVector4i", Args(&[DType(CVector4i)]), CString),
    ("GetStruggle", Args(&[DType(Unknown)]), Unknown),
    ("GetStrugglePhase", Args(&[DType(Unknown)]), Unknown),
    ("GetStruggleType", Args(&[DType(Unknown)]), Unknown),
    ("GetSuggestionType", Args(&[DType(Unknown)]), Unknown),
    ("GetTerrain", Args(&[IType(Item::Terrain)]), Unknown),
    ("GetTicksSinceLastProgress", Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("GetTimeAnyoneUnpause", Args(&[]), int32),
    ("GetTimeBetweenDates", Args(&[DType(Date), DType(Date)]), CString),
    ("GetTimeDifferenceWithDays", Args(&[DType(int32)]), CString),
    ("GetTotalDaysInMonth", Args(&[DType(Unknown)]), int32),
    ("GetTrait", Args(&[IType(Item::Trait)]), Ck3(Trait)),
    ("GetTraitGroup", Args(&[DType(Unknown)]), Unknown),
    ("GetTraits", Args(&[]), Unknown),
    ("GetTraitsWithFlag", Args(&[DType(Unknown)]), Unknown),
    ("GetTraitsWithoutFlag", Args(&[DType(Unknown)]), Unknown),
    ("GetTravelOption", Args(&[DType(Unknown)]), Unknown),
    ("GetTravelPointOfInterestType", Args(&[DType(Unknown)]), void),
    ("GetVarTimeRemaining", Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("GetVassalContractType", Args(&[DType(Unknown)]), Unknown),
    ("GetVassalStance", Args(&[IType(Item::VassalStance)]), Unknown),
    ("GetViewHistoryTooltip", Args(&[]), CString),
    ("GetZoomLevel", Args(&[]), int32),
    ("GfxGetSkins", Args(&[]), Unknown),
    ("GfxSetActiveSkin", Args(&[DType(Unknown)]), void),
    ("GfxSkinIsActive", Args(&[DType(Unknown)]), bool),
    ("GoToFrontend", Args(&[]), void),
    ("GreaterThanOrEqualTo_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("GreaterThanOrEqualTo_float", Args(&[DType(float), DType(float)]), bool),
    ("GreaterThanOrEqualTo_int32", Args(&[DType(int32), DType(int32)]), bool),
    ("GreaterThanOrEqualTo_uint32", Args(&[DType(uint32), DType(uint32)]), bool),
    ("GreaterThan_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("GreaterThan_float", Args(&[DType(float), DType(float)]), bool),
    ("GreaterThan_int32", Args(&[DType(int32), DType(int32)]), bool),
    ("GreaterThan_uint32", Args(&[DType(uint32), DType(uint32)]), bool),
    ("HasCharacterInteractionCategory", Args(&[DType(Unknown)]), bool),
    ("HasDifferentChecksumThanCompiled", Args(&[]), bool),
    ("HasDlcFeature", Args(&[IType(Item::DlcFeature)]), bool),
    ("HasErrors", Args(&[]), bool),
    ("HasGameStartedForTheFirstTime", Args(&[]), bool),
    ("HasHostError", Args(&[]), bool),
    ("HasLoadedMods", Args(&[]), bool),
    ("HasOpenResetReactiveTutorialPopup", Args(&[]), bool),
    ("HasViewHistory", Args(&[]), bool),
    ("HighlightStruggle", Args(&[DType(Unknown)]), void),
    ("HoursPerDay", Args(&[]), int32),
    ("InDebugMode", Args(&[]), bool),
    ("InReleaseMode", Args(&[]), bool),
    ("IntToFixedPoint", Args(&[DType(Unknown)]), CFixedPoint),
    ("IntToFloat", Args(&[DType(Unknown)]), float),
    ("IntToFrameIndex", Args(&[DType(Unknown)]), int32),
    ("IntToUnsigned", Args(&[DType(Unknown)]), uint32),
    ("IsAutoSaving", Args(&[]), bool),
    ("IsBottomLeftWindowOpen", Args(&[]), bool),
    ("IsBottomWindowOpen", Args(&[]), bool),
    ("IsBuildDebug", Args(&[]), bool),
    ("IsCameraRestrictionsEnabled", Args(&[]), bool),
    ("IsCenterWindowOpen", Args(&[]), bool),
    ("IsContractBlockedFromBeingModified", Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("IsContractBlockedFromBeingModifiedText", Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("IsDataModelEmpty", Args(&[DType(Unknown)]), bool),
    ("IsDateAfter", Args(&[DType(Date), DType(Date)]), bool),
    ("IsDateBefore", Args(&[DType(Date), DType(Date)]), bool),
    ("IsDateBetween", Args(&[DType(Date), DType(Date), DType(Date)]), bool),
    ("IsDateToday", Args(&[DType(Date)]), bool),
    ("IsDefaultGUIMode", Args(&[]), bool),
    ("IsDesignatedHeir", Args(&[DType(Ck3(Character))]), bool),
    ("IsExploringRealms", Args(&[]), bool),
    ("IsFullScreenWindowOpen", Args(&[]), bool),
    ("IsGameChecksumOk", Args(&[]), bool),
    ("IsGameOver", Args(&[]), bool),
    ("IsGamePaused", Args(&[]), bool),
    ("IsGameViewDataShown", Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("IsGameViewOpen", Args(&[DType(Unknown)]), bool),
    ("IsHolyOrderDetailViewShown", Args(&[DType(Unknown)]), bool),
    ("IsHost", Args(&[]), bool),
    ("IsInGame", Args(&[]), bool),
    ("IsInteractionConfirmationWindowOpen", Args(&[]), bool),
    ("IsInteractionMenuOpenForCharacter", Args(&[DType(Unknown)]), bool),
    ("IsIronmanEnabled", Args(&[]), bool),
    ("IsLeftWindowOpen", Args(&[]), bool),
    ("IsMachineRulerDesigning", Args(&[DType(Unknown)]), bool),
    ("IsManuallyPaused", Args(&[]), bool),
    ("IsMapInteractionConfirmationWindowOpen", Args(&[]), bool),
    ("IsMapMode", Args(&[DType(Unknown)]), bool),
    ("IsMercenaryCompanyDetailViewShown", Args(&[DType(Unknown)]), bool),
    ("IsObserver", Args(&[]), bool),
    ("IsOverviewWindowOpen", Args(&[]), bool),
    ("IsPauseMenuShown", Args(&[]), bool),
    ("IsPausedByEvent", Args(&[]), bool),
    ("IsPausedByMe", Args(&[]), bool),
    ("IsPreparationLobby", Args(&[]), bool),
    ("IsRightSubwindowOpen", Args(&[]), bool),
    ("IsRightWindowNoSidebarOpen", Args(&[]), bool),
    ("IsRightWindowOpen", Args(&[]), bool),
    ("IsTutorialTagOpen", Args(&[DType(Unknown)]), bool),
    ("IsValidDate", Args(&[DType(Date)]), bool),
    ("JoinText", Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("JominiAccessPlayerJoinRequests", Args(&[]), Unknown),
    ("JominiAreAchievementsAvailable", Args(&[]), bool),
    ("JominiGetAchievementsNotAvailableString", Args(&[]), CString),
    ("JominiGetMultiplayerAccessibleString", Args(&[]), CString),
    ("JominiHasPlayerJoinRequests", Args(&[]), bool),
    ("JominiIsHostOrLocal", Args(&[]), bool),
    ("JominiIsMultiplayerAccessible", Args(&[]), bool),
    ("JominiMultiplayerIsCrossplayEnabled", Args(&[]), bool),
    ("JominiMultiplayerIsCrossplayFilterAvailable", Args(&[]), bool),
    ("JominiPlayer", Args(&[]), Unknown),
    ("LessThanOrEqualTo_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("LessThanOrEqualTo_float", Args(&[DType(float), DType(float)]), bool),
    ("LessThanOrEqualTo_int32", Args(&[DType(int32), DType(int32)]), bool),
    ("LessThanOrEqualTo_uint32", Args(&[DType(uint32), DType(uint32)]), bool),
    ("LessThan_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("LessThan_float", Args(&[DType(float), DType(float)]), bool),
    ("LessThan_int32", Args(&[DType(int32), DType(int32)]), bool),
    ("LessThan_uint32", Args(&[DType(uint32), DType(uint32)]), bool),
    ("Localize", Args(&[DType(Unknown)]), CString),
    ("MakeScopeBool", Args(&[DType(Unknown)]), Scope),
    ("MakeScopeFlag", Args(&[DType(Unknown)]), Scope),
    ("MakeScopeValue", Args(&[DType(Unknown)]), Scope),
    ("MapEditorHasGameMapMode", Args(&[]), bool),
    ("Max_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Max_float", Args(&[DType(float), DType(float)]), float),
    ("Max_int32", Args(&[DType(int32), DType(int32)]), int32),
    ("Max_uint32", Args(&[DType(uint32), DType(uint32)]), uint32),
    ("Min_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Min_float", Args(&[DType(float), DType(float)]), float),
    ("Min_int32", Args(&[DType(int32), DType(int32)]), int32),
    ("Min_uint32", Args(&[DType(uint32), DType(uint32)]), uint32),
    ("MonthsPerYear", Args(&[]), int32),
    ("Multiply_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Multiply_CVector2f", Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Multiply_float", Args(&[DType(float), DType(float)]), float),
    ("Multiply_int32", Args(&[DType(int32), DType(int32)]), int32),
    ("Multiply_uint32", Args(&[DType(uint32), DType(uint32)]), uint32),
    ("NOP", Args(&[]), void),
    ("Nbsp", Args(&[]), CString),
    ("Negate_CFixedPoint", Args(&[DType(CFixedPoint)]), CFixedPoint),
    ("Negate_float", Args(&[DType(float)]), float),
    ("Negate_int32", Args(&[DType(int32)]), int32),
    ("Not", Args(&[DType(bool)]), bool),
    ("NotEqualTo_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("NotEqualTo_CVector2f", Args(&[DType(CVector2f), DType(CVector2f)]), bool),
    ("NotEqualTo_float", Args(&[DType(float), DType(float)]), bool),
    ("NotEqualTo_int32", Args(&[DType(int32), DType(int32)]), bool),
    ("NotEqualTo_uint32", Args(&[DType(uint32), DType(uint32)]), bool),
    ("NumberOrErrors", Args(&[]), int32),
    ("ObjectsEqual", Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("OnCreateAccount", Args(&[]), void),
    ("OnDecreaseGameSpeed", Args(&[]), void),
    ("OnGoToPlayerCapital", Args(&[]), void),
    ("OnIncreaseGameSpeed", Args(&[]), void),
    ("OnPause", Args(&[]), void),
    ("OnPauseMenu", Args(&[]), void),
    ("OnRaiseEventTroops", Args(&[DType(Unknown)]), void),
    ("OnToggleLoginWindow", Args(&[]), void),
    ("OpenAchievements", Args(&[]), void),
    ("OpenCharacterInteraction", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("OpenDesignateHeirWindow", Args(&[]), Unknown),
    ("OpenDynastyCustomizationWindow", Args(&[DType(Unknown)]), void),
    ("OpenErrorLog", Args(&[]), void),
    ("OpenFromViewHistory", Args(&[]), void),
    ("OpenGameRules", Args(&[]), void),
    ("OpenGameView", Args(&[DType(Unknown)]), void),
    ("OpenGameViewData", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("OpenHolyOrderDetailView", Args(&[DType(Unknown)]), void),
    ("OpenHouseCustomizationWindow", Args(&[DType(Unknown)]), void),
    ("OpenMercenaryCompanyDetailView", Args(&[DType(Unknown)]), void),
    ("OpenSetAcclaimedView", Args(&[DType(Unknown)]), void),
    ("OpenSuccessionElectionWindowForTitle", Args(&[DType(Unknown)]), Unknown),
    ("OpenSuccessionLawChangeWindow", Args(&[DType(Unknown)]), Unknown),
    ("OpenTitleCustomizationWindow", Args(&[DType(Unknown)]), void),
    ("Or", Args(&[DType(bool), DType(bool)]), bool),
    ("POPSStatusGetLoginStatus", Args(&[]), CUTF8String),
    ("POPSStatusIsAccountConnected", Args(&[]), bool),
    ("POPSStatusIsLoggedIn", Args(&[]), bool),
    ("POPSStatusIsLoggingIn", Args(&[]), bool),
    ("POPSStatusIsOffline", Args(&[]), bool),
    ("POPSStatusIsSupportConnectedAccount", Args(&[]), bool),
    ("POPStatusGetUserEmailMasked", Args(&[]), CUTF8String),
    ("POPStatusGetUserName", Args(&[]), CUTF8String),
    ("POPStatusIsUserNameEmpty", Args(&[]), bool),
    ("PdxClearEditBoxText", Args(&[DType(Unknown)]), void),
    ("PdxGetProfilerNames", Args(&[]), Unknown),
    ("PdxGetWidgetScreenSize", Args(&[DType(Unknown)]), CVector2f),
    ("PdxGuiDestroyWidget", Args(&[DType(Unknown)]), void),
    ("PdxGuiEditorMessageBox", Args(&[DType(Unknown)]), void),
    ("PdxGuiInterruptAllAnimations", Args(&[DType(Unknown)]), void),
    ("PdxGuiInterruptThenTriggerAllAnimations", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("PdxGuiTriggerAllAnimations", Args(&[DType(Unknown)]), void),
    ("PdxProfilerFilterNext", Args(&[]), void),
    ("PdxProfilerFilterPrev", Args(&[]), void),
    ("PdxProfilerFilterTimers", Args(&[]), void),
    ("PdxProfilerGetCurrentFrame", Args(&[]), int32),
    ("PdxProfilerGetFrameTimeMs", Args(&[]), float),
    ("PdxProfilerGetNsPerTick", Args(&[]), float),
    ("PdxProfilerGuiGraphLinesEnabled", Args(&[]), bool),
    ("PdxProfilerGuiToggleGraphLines", Args(&[]), void),
    ("PdxProfilerGuiToggleStats", Args(&[]), void),
    ("PdxProfilerGuiTrackCurrentFrame", Args(&[]), void),
    ("PdxProfilerGuiWriteFrameCSV", Args(&[]), void),
    ("PdxProfilerIsRecording", Args(&[]), bool),
    ("PdxProfilerSelectThread", Args(&[]), void),
    ("PdxProfilerSetFrame", Args(&[]), void),
    ("PdxProfilerToggleRecording", Args(&[]), void),
    ("PlaySfxEvent", Args(&[DType(Unknown)]), void),
    ("PlayerCanDisbandAll", Args(&[]), bool),
    ("PlayerCanRaiseAnyMenAtArmsRallyPoint", Args(&[]), bool),
    ("PlayerCanRaiseAnyRaiderRallyPoint", Args(&[]), bool),
    ("PlayerCanRaiseAnyRallyPoint", Args(&[]), bool),
    ("PlayerDisbandAll", Args(&[]), void),
    ("PlayerIsHost", Args(&[]), bool),
    ("PlayerRaiseAllMenAtArmsRegiments", Args(&[]), void),
    ("PlayerRaiseAllRaidRegiments", Args(&[]), void),
    ("PlayerRaiseAllRegiments", Args(&[]), void),
    ("PlayerShouldDisbandAll", Args(&[]), bool),
    ("RaiseHolyOrder", Args(&[DType(Unknown)]), void),
    ("RaiseMercenaryCompany", Args(&[DType(Unknown)]), void),
    ("RefreshIllustration", Args(&[]), void),
    ("ReleaseMode", Args(&[]), bool),
    ("RepeatedItem", Args(&[DType(Unknown)]), Unknown),
    ("ReturnToMenu", Args(&[]), void),
    ("ScaleToFitElementInside", Args(&[DType(Unknown), DType(Unknown)]), float),
    ("ScaleToFitElementOutside", Args(&[DType(Unknown), DType(Unknown)]), float),
    ("SelectEnumWithString", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("SelectLocalization", Args(&[DType(bool), DType(CString), DType(CString)]), CString),
    ("Select_CFixedPoint", Args(&[DType(bool), DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Select_CString", Args(&[DType(bool), DType(CString), DType(CString)]), CString),
    ("Select_CVector2f", Args(&[DType(bool), DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Select_CVector2i", Args(&[DType(bool), DType(CVector2i), DType(CVector2i)]), CVector2i),
    ("Select_CVector3f", Args(&[DType(bool), DType(CVector3f), DType(CVector3f)]), CVector3f),
    ("Select_CVector3i", Args(&[DType(bool), DType(CVector3i), DType(CVector3i)]), CVector3i),
    ("Select_CVector4f", Args(&[DType(bool), DType(CVector4f), DType(CVector4f)]), CVector4f),
    ("Select_CVector4i", Args(&[DType(bool), DType(CVector4i), DType(CVector4i)]), CVector4i),
    ("Select_float", Args(&[DType(bool), DType(float), DType(float)]), float),
    ("Select_int16", Args(&[DType(bool), DType(int16), DType(int16)]), int16),
    ("Select_int32", Args(&[DType(bool), DType(int32), DType(int32)]), int32),
    ("Select_int8", Args(&[DType(bool), DType(int8), DType(int8)]), int8),
    ("Select_uint16", Args(&[DType(bool), DType(uint16), DType(uint16)]), uint16),
    ("Select_uint32", Args(&[DType(bool), DType(uint32), DType(uint32)]), uint32),
    ("Select_uint8", Args(&[DType(bool), DType(uint8), DType(uint8)]), uint8),
    ("SetCameraRestrictionsEnabled", Args(&[DType(Unknown)]), void),
    ("SetGameSpeed", Args(&[DType(Unknown)]), void),
    ("SetIronmanEnabledStatus", Args(&[DType(Unknown)]), void),
    ("SetMapMode", Args(&[DType(Unknown)]), void),
    ("SetRandomPlayableObserverCharacter", Args(&[]), void),
    ("ShouldPromptForRulerDesigner", Args(&[]), bool),
    ("ShouldShowAnimationInfo", Args(&[]), bool),
    ("ShouldShowCharacterDebugInfo", Args(&[]), bool),
    ("ShouldShowCharacterTooltips", Args(&[]), bool),
    ("ShouldShowSegmentedControlForSetting", Args(&[DType(Unknown)]), bool),
    ("ShowAppointCourtPosition", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("ShowAppointCourtPositionIfNoEmployee", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("ShowCourtPositionAppointOrReplace", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("ShowCourtPositions", Args(&[DType(Unknown)]), void),
    ("ShowingSuccession", Args(&[]), bool),
    ("SinglePlayerShowingPausedSuccession", Args(&[]), bool),
    ("SinglePlayerShowingSuccession", Args(&[]), bool),
    ("StringIsEmpty", Args(&[DType(CString)]), bool),
    ("Subtract_CFixedPoint", Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Subtract_CVector2f", Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Subtract_float", Args(&[DType(float), DType(float)]), float),
    ("Subtract_int32", Args(&[DType(int32), DType(int32)]), int32),
    ("Subtract_uint32", Args(&[DType(uint32), DType(uint32)]), uint32),
    ("TextureListFormatSize", Args(&[DType(Unknown)]), CString),
    ("TextureListFormatkB", Args(&[DType(Unknown)]), CString),
    ("ToggleEncyclopedia", Args(&[]), void),
    ("ToggleGameView", Args(&[DType(Unknown)]), void),
    ("ToggleGameViewData", Args(&[DType(Unknown), DType(Unknown)]), void),
    ("ToggleHolyOrderDetailView", Args(&[DType(Unknown)]), void),
    ("ToggleMapEditorGameMapModeActive", Args(&[]), void),
    ("ToggleMercenaryCompanyDetailView", Args(&[DType(Unknown)]), void),
    ("ToggleOnCoatOfArmsClick", Args(&[DType(Unknown)]), void),
    ("TryStartRulerDesigning", Args(&[DType(Unknown)]), void),
    ("Unfocus", Args(&[DType(Unknown)]), void),
    ("UsesTimerLocking", Args(&[]), bool),
    ("WatchWindowsEnabled", Args(&[]), bool),
    ("WeeksPerYear", Args(&[]), int32),
]
