use strum_macros::{Display, EnumString};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Display, EnumString, Hash)]
#[strum(serialize_all = "kebab-case")]
pub enum ErrorKey {
    Config,
    ReadError,
    ParseError,
    BracePlacement,
    Packaging,
    Validation,
    Filename,
    Encoding,
    Localization,
    DuplicateItem,
    DuplicateField,
    NameConflict,
    EventNamespace,
    MissingLocalization,
    MissingFile,
    MissingItem,
    MissingPerspective,
    WrongGender,
    Conflict,
    ImageFormat,
    Unneeded,
    Scopes,
    Crash,
    Range,
    Tooltip,
    Tidying,
    Rivers,
    Modifiers,
    Macro,
    History,
    Logic,
    Bugs,
    Datafunctions,
    Removed,
    FieldMissing,
    UnknownField,
    TitleTier,
    Colors,
    ComplexTrigger,
    UnusedLocalization,
    NameCollision,
    UnknownList,

    PrincesOfDarkness,

    Internal,
}
